//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Aksesuar_Model : XPObject
    {
        ModelKarti fModelKarti;
        
        public ModelKarti ModelKarti
        {
            get { return fModelKarti; }
            set { SetPropertyValue<ModelKarti>(nameof(ModelKarti), ref fModelKarti, value); }
        }
        Aksesuarlar fAksesuar;
        public Aksesuarlar Aksesuar
        {
            get { return fAksesuar; }
            set { SetPropertyValue<Aksesuarlar>(nameof(Aksesuar), ref fAksesuar, value); }
        }
        string fKullanılacakAdet;
        public string KullanılacakAdet
        {
            get { return fKullanılacakAdet; }
            set { SetPropertyValue<string>(nameof(KullanılacakAdet), ref fKullanılacakAdet, value); }
        }
    }

}
