//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Aksesuarlar : XPObject
    {
        AksesuarKategori fKategori;
        public AksesuarKategori Kategori
        {
            get { return fKategori; }
            set { SetPropertyValue<AksesuarKategori>(nameof(Kategori), ref fKategori, value); }
        }
        string fBeden;
        public string Beden
        {
            get { return fBeden; }
            set { SetPropertyValue<string>(nameof(Beden), ref fBeden, value); }
        }
        string fAdi;
        public string Adi
        {
            get { return fAdi; }
            set { SetPropertyValue<string>(nameof(Adi), ref fAdi, value); }
        }
        string fEn;
        public string En
        {
            get { return fEn; }
            set { SetPropertyValue<string>(nameof(En), ref fEn, value); }
        }
        string fBoy;
        public string Boy
        {
            get { return fBoy; }
            set { SetPropertyValue<string>(nameof(Boy), ref fBoy, value); }
        }
        string fKalinlik;
        public string Kalinlik
        {
            get { return fKalinlik; }
            set { SetPropertyValue<string>(nameof(Kalinlik), ref fKalinlik, value); }
        }
        Renkler fRenk;
        public Renkler Renk
        {
            get { return fRenk; }
            set { SetPropertyValue<Renkler>(nameof(Renk), ref fRenk, value); }
        }
        byte[] fResmi;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    ListViewImageEditorCustomHeight = 40)]
        public byte[] Resmi
        {
            get { return fResmi; }
            set { SetPropertyValue<byte[]>(nameof(Resmi), ref fResmi, value); }
        }
        SiparisKarti fSiparisKarti;
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
        [PersistentAlias("[Kategori.Kategori] + ' Bdn=' + [Beden] + ' Boy=' + [Boy] + ' En' + [En] + ' Klnlık=' + [Kalinlik] + ' Rnk=' + [Renk.RenkAdi]")]
        public string Aksesuar
        {
            get { return (string)(EvaluateAlias(nameof(Aksesuar))); }
        }
        EtiketTur fEtiketTuru;
        public EtiketTur EtiketTuru
        {
            get { return fEtiketTuru; }
            set { SetPropertyValue<EtiketTur>(nameof(EtiketTuru), ref fEtiketTuru, value); }
        }
        Yikamatalimaticerik fYikamaTalimat;
        public Yikamatalimaticerik YikamaTalimat
        {
            get { return fYikamaTalimat; }
            set { SetPropertyValue<Yikamatalimaticerik>(nameof(YikamaTalimat), ref fYikamaTalimat, value); }
        }
        [Association(@"AksesuarlarReferencesAksesuarlar")]
        public XPCollection<Aksesuarlar> AksesuarlarCollection { get { return GetCollection<Aksesuarlar>(nameof(AksesuarlarCollection)); } }
        [Association(@"AksesuarlarReferencesAksesuarlar")]
        public XPCollection<Aksesuarlar> AksesuarlarCollection1 { get { return GetCollection<Aksesuarlar>(nameof(AksesuarlarCollection1)); } }
        [Association(@"SiparisKartiReferencesAksesuarlar")]
        public XPCollection<SiparisKarti> SiparisKartis { get { return GetCollection<SiparisKarti>(nameof(SiparisKartis)); } }
    }

}
