//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Baski : XPObject
    {
        SiparisKarti fSiparisKarti;
        [Association(@"BaskiReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
        ModelBolge fBolge;
        public ModelBolge Bolge
        {
            get { return fBolge; }
            set { SetPropertyValue<ModelBolge>(nameof(Bolge), ref fBolge, value); }
        }
        BaskiCinsi fBaskiTuru;
        public BaskiCinsi BaskiTuru
        {
            get { return fBaskiTuru; }
            set { SetPropertyValue<BaskiCinsi>(nameof(BaskiTuru), ref fBaskiTuru, value); }
        }
        byte[] fResmi;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    ListViewImageEditorCustomHeight = 40)]
        public byte[] Resmi
        {
            get { return fResmi; }
            set { SetPropertyValue<byte[]>(nameof(Resmi), ref fResmi, value); }
        }
        string fAciklama;
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
        string fFiyat;
        public string Fiyat
        {
            get { return fFiyat; }
            set { SetPropertyValue<string>(nameof(Fiyat), ref fFiyat, value); }
        }
        string fBirimi;
        public string Birimi
        {
            get { return fBirimi; }
            set { SetPropertyValue<string>(nameof(Birimi), ref fBirimi, value); }
        }
    }

}
