//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class BedenGrubu : XPObject
    {
        string fBedenGrup;
        public string BedenGrup
        {
            get { return fBedenGrup; }
            set { SetPropertyValue<string>(nameof(BedenGrup), ref fBedenGrup, value); }
        }
    }

}
