//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Bedenler : XPObject
    {
        bool fXXS;
        public bool XXS
        {
            get { return fXXS; }
            set { SetPropertyValue<bool>(nameof(XXS), ref fXXS, value); }
        }
        BedenGrubu fBedenGrubu;
        public BedenGrubu BedenGrubu
        {
            get { return fBedenGrubu; }
            set { SetPropertyValue<BedenGrubu>(nameof(BedenGrubu), ref fBedenGrubu, value); }
        }
        bool fXS;
        public bool XS
        {
            get { return fXS; }
            set { SetPropertyValue<bool>(nameof(XS), ref fXS, value); }
        }
        bool fS;
        public bool S
        {
            get { return fS; }
            set { SetPropertyValue<bool>(nameof(S), ref fS, value); }
        }
        bool fM;
        public bool M
        {
            get { return fM; }
            set { SetPropertyValue<bool>(nameof(M), ref fM, value); }
        }
        bool fL;
        public bool L
        {
            get { return fL; }
            set { SetPropertyValue<bool>(nameof(L), ref fL, value); }
        }
        bool fXL;
        public bool XL
        {
            get { return fXL; }
            set { SetPropertyValue<bool>(nameof(XL), ref fXL, value); }
        }
        bool fXXL;
        public bool XXL
        {
            get { return fXXL; }
            set { SetPropertyValue<bool>(nameof(XXL), ref fXXL, value); }
        }
        bool fB3XL;
        [DevExpress.Xpo.DisplayName(@"3XL")]
        public bool B3XL
        {
            get { return fB3XL; }
            set { SetPropertyValue<bool>(nameof(B3XL), ref fB3XL, value); }
        }
        bool fB4XL;
        [DevExpress.Xpo.DisplayName(@"4XL")]
        public bool B4XL
        {
            get { return fB4XL; }
            set { SetPropertyValue<bool>(nameof(B4XL), ref fB4XL, value); }
        }
        bool fB5XL;
        [DevExpress.Xpo.DisplayName(@"5XL")]
        public bool B5XL
        {
            get { return fB5XL; }
            set { SetPropertyValue<bool>(nameof(B5XL), ref fB5XL, value); }
        }
        bool fB6XL;
        [DevExpress.Xpo.DisplayName(@"6XL")]
        public bool B6XL
        {
            get { return fB6XL; }
            set { SetPropertyValue<bool>(nameof(B6XL), ref fB6XL, value); }
        }
        bool fB4;
        public bool B4
        {
            get { return fB4; }
            set { SetPropertyValue<bool>(nameof(B4), ref fB4, value); }
        }
        bool fB6;
        public bool B6
        {
            get { return fB6; }
            set { SetPropertyValue<bool>(nameof(B6), ref fB6, value); }
        }
        bool fB8;
        public bool B8
        {
            get { return fB8; }
            set { SetPropertyValue<bool>(nameof(B8), ref fB8, value); }
        }
        bool fB10;
        public bool B10
        {
            get { return fB10; }
            set { SetPropertyValue<bool>(nameof(B10), ref fB10, value); }
        }
        bool fB12;
        public bool B12
        {
            get { return fB12; }
            set { SetPropertyValue<bool>(nameof(B12), ref fB12, value); }
        }
        bool fB14;
        public bool B14
        {
            get { return fB14; }
            set { SetPropertyValue<bool>(nameof(B14), ref fB14, value); }
        }
        bool fB16;
        public bool B16
        {
            get { return fB16; }
            set { SetPropertyValue<bool>(nameof(B16), ref fB16, value); }
        }
        bool fB18;
        public bool B18
        {
            get { return fB18; }
            set { SetPropertyValue<bool>(nameof(B18), ref fB18, value); }
        }
        bool fB20;
        public bool B20
        {
            get { return fB20; }
            set { SetPropertyValue<bool>(nameof(B20), ref fB20, value); }
        }
        bool fB22;
        public bool B22
        {
            get { return fB22; }
            set { SetPropertyValue<bool>(nameof(B22), ref fB22, value); }
        }
        bool fB24;
        public bool B24
        {
            get { return fB24; }
            set { SetPropertyValue<bool>(nameof(B24), ref fB24, value); }
        }
        bool fB26;
        public bool B26
        {
            get { return fB26; }
            set { SetPropertyValue<bool>(nameof(B26), ref fB26, value); }
        }
        bool fB28;
        public bool B28
        {
            get { return fB28; }
            set { SetPropertyValue<bool>(nameof(B28), ref fB28, value); }
        }
        bool fB30;
        public bool B30
        {
            get { return fB30; }
            set { SetPropertyValue<bool>(nameof(B30), ref fB30, value); }
        }
        bool fB32;
        public bool B32
        {
            get { return fB32; }
            set { SetPropertyValue<bool>(nameof(B32), ref fB32, value); }
        }
        bool fB34;
        public bool B34
        {
            get { return fB34; }
            set { SetPropertyValue<bool>(nameof(B34), ref fB34, value); }
        }
        bool fB36;
        public bool B36
        {
            get { return fB36; }
            set { SetPropertyValue<bool>(nameof(B36), ref fB36, value); }
        }
        bool fY5_6;
        public bool Y5_6
        {
            get { return fY5_6; }
            set { SetPropertyValue<bool>(nameof(Y5_6), ref fY5_6, value); }
        }
        bool fY7_8;
        public bool Y7_8
        {
            get { return fY7_8; }
            set { SetPropertyValue<bool>(nameof(Y7_8), ref fY7_8, value); }
        }
        bool fY9_10;
        public bool Y9_10
        {
            get { return fY9_10; }
            set { SetPropertyValue<bool>(nameof(Y9_10), ref fY9_10, value); }
        }
        bool fY11_12;
        public bool Y11_12
        {
            get { return fY11_12; }
            set { SetPropertyValue<bool>(nameof(Y11_12), ref fY11_12, value); }
        }
        bool fY13;
        [DevExpress.Xpo.DisplayName(@"13 Yaş")]
        public bool Y13
        {
            get { return fY13; }
            set { SetPropertyValue<bool>(nameof(Y13), ref fY13, value); }
        }
        bool fB56;
        public bool B56
        {
            get { return fB56; }
            set { SetPropertyValue<bool>(nameof(B56), ref fB56, value); }
        }
        bool fB62;
        public bool B62
        {
            get { return fB62; }
            set { SetPropertyValue<bool>(nameof(B62), ref fB62, value); }
        }
        bool fB68;
        public bool B68
        {
            get { return fB68; }
            set { SetPropertyValue<bool>(nameof(B68), ref fB68, value); }
        }
        bool fB74;
        public bool B74
        {
            get { return fB74; }
            set { SetPropertyValue<bool>(nameof(B74), ref fB74, value); }
        }
        bool fB80;
        public bool B80
        {
            get { return fB80; }
            set { SetPropertyValue<bool>(nameof(B80), ref fB80, value); }
        }
        bool fB86;
        public bool B86
        {
            get { return fB86; }
            set { SetPropertyValue<bool>(nameof(B86), ref fB86, value); }
        }
        bool fB92;
        public bool B92
        {
            get { return fB92; }
            set { SetPropertyValue<bool>(nameof(B92), ref fB92, value); }
        }
        bool fB98;
        public bool B98
        {
            get { return fB98; }
            set { SetPropertyValue<bool>(nameof(B98), ref fB98, value); }
        }
        bool fB104;
        public bool B104
        {
            get { return fB104; }
            set { SetPropertyValue<bool>(nameof(B104), ref fB104, value); }
        }
        bool fB110;
        public bool B110
        {
            get { return fB110; }
            set { SetPropertyValue<bool>(nameof(B110), ref fB110, value); }
        }
        bool fB116;
        public bool B116
        {
            get { return fB116; }
            set { SetPropertyValue<bool>(nameof(B116), ref fB116, value); }
        }
        bool fB122;
        public bool B122
        {
            get { return fB122; }
            set { SetPropertyValue<bool>(nameof(B122), ref fB122, value); }
        }
        bool fB128;
        public bool B128
        {
            get { return fB128; }
            set { SetPropertyValue<bool>(nameof(B128), ref fB128, value); }
        }
        bool fB134;
        public bool B134
        {
            get { return fB134; }
            set { SetPropertyValue<bool>(nameof(B134), ref fB134, value); }
        }
        bool fB140;
        public bool B140
        {
            get { return fB140; }
            set { SetPropertyValue<bool>(nameof(B140), ref fB140, value); }
        }
        bool fB156;
        public bool B156
        {
            get { return fB156; }
            set { SetPropertyValue<bool>(nameof(B156), ref fB156, value); }
        }
        string fAciklama;
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
    }

}
