//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    public enum CariHareketTipi { Fatura, Odeme }

    [DefaultClassOptions]
    [NavigationItem("Finans Yönetimi")]
    public partial class CariHareket : XPObject
    {
        public CariHareket(Session session) : base(session) { }

        Musteriler fMusteri;
        [Association("Musteri-CariHareketler")]
        public Musteriler Musteri
        {
            get { return fMusteri; }
            set { SetPropertyValue(nameof(Musteri), ref fMusteri, value); }
        }

        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue(nameof(Tarih), ref fTarih, value); }
        }

        CariHareketTipi fHareketTipi;
        public CariHareketTipi HareketTipi
        {
            get { return fHareketTipi; }
            set { SetPropertyValue(nameof(HareketTipi), ref fHareketTipi, value); }
        }

        decimal fBorc;
        public decimal Borc
        {
            get { return fBorc; }
            set { SetPropertyValue(nameof(Borc), ref fBorc, value); }
        }

        decimal fAlacak;
        public decimal Alacak
        {
            get { return fAlacak; }
            set { SetPropertyValue(nameof(Alacak), ref fAlacak, value); }
        }

        string fAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue(nameof(Aciklama), ref fAciklama, value); }
        }

        [PersistentAlias("Borc - Alacak")]
        public decimal Tutar
        {
            get { return (decimal)(EvaluateAlias(nameof(Tutar)) ?? 0m); }
        }
    }
}
