//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    [DefaultClassOptions]
    public partial class DestekMesaji : XPObject
    {
        public DestekMesaji(Session session) : base(session) { }

        MusteriDestekTalebi fDestekTalebi;
        [Association("DestekTalebi-Mesajlar")]
        public MusteriDestekTalebi DestekTalebi
        {
            get { return fDestekTalebi; }
            set { SetPropertyValue(nameof(DestekTalebi), ref fDestekTalebi, value); }
        }

        DateTime fGonderimTarihi;
        public DateTime GonderimTarihi
        {
            get { return fGonderimTarihi; }
            set { SetPropertyValue(nameof(GonderimTarihi), ref fGonderimTarihi, value); }
        }

        string fMesaj;
        [Size(SizeAttribute.Unlimited)]
        public string Mesaj
        {
            get { return fMesaj; }
            set { SetPropertyValue(nameof(Mesaj), ref fMesaj, value); }
        }

        string fGonderen;
        public string Gonderen
        {
            get { return fGonderen; }
            set { SetPropertyValue(nameof(Gonderen), ref fGonderen, value); }
        }
    }
}
