//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Dikim : XPObject
    {
        string fPartiNo;
        public string PartiNo
        {
            get { return fPartiNo; }
            set { SetPropertyValue<string>(nameof(PartiNo), ref fPartiNo, value); }
        }
        int fVerilenAdet;
        public int VerilenAdet
        {
            get { return fVerilenAdet; }
            set { SetPropertyValue<int>(nameof(VerilenAdet), ref fVerilenAdet, value); }
        }
        DateTime fBaslamaTarih;
        public DateTime BaslamaTarih
        {
            get { return fBaslamaTarih; }
            set { SetPropertyValue<DateTime>(nameof(BaslamaTarih), ref fBaslamaTarih, value); }
        }
        DateTime fBitisTarihi;
        public DateTime BitisTarihi
        {
            get { return fBitisTarihi; }
            set { SetPropertyValue<DateTime>(nameof(BitisTarihi), ref fBitisTarihi, value); }
        }
        int fCikanAdet;
        public int CikanAdet
        {
            get { return fCikanAdet; }
            set { SetPropertyValue<int>(nameof(CikanAdet), ref fCikanAdet, value); }
        }
        Bandi fBandi;
        public Bandi Bandi
        {
            get { return fBandi; }
            set { SetPropertyValue<Bandi>(nameof(Bandi), ref fBandi, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"DikimReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
    }

}
