//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Etiketler : XPObject
    {
        EtiketTur fEtiketTur;
        public EtiketTur EtiketTur
        {
            get { return fEtiketTur; }
            set { SetPropertyValue<EtiketTur>(nameof(EtiketTur), ref fEtiketTur, value); }
        }
        byte[] fEtiketResim;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    ListViewImageEditorCustomHeight = 40)]
        public byte[] EtiketResim
        {
            get { return fEtiketResim; }
            set { SetPropertyValue<byte[]>(nameof(EtiketResim), ref fEtiketResim, value); }
        }
        Yikamatalimaticerik fYikamaTalimati;
        public Yikamatalimaticerik YikamaTalimati
        {
            get { return fYikamaTalimati; }
            set { SetPropertyValue<Yikamatalimaticerik>(nameof(YikamaTalimati), ref fYikamaTalimati, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"EtiketlerReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
    }

}
