//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class FasonTakip : XPObject
    {
        SiparisOperasyon fSiparisOperasyon;
        [Association("SiparisOperasyon-FasonTakip")]
        public SiparisOperasyon SiparisOperasyon
        {
            get { return fSiparisOperasyon; }
            set { SetPropertyValue(nameof(SiparisOperasyon), ref fSiparisOperasyon, value); }
        }

        Firmalar fFasonFirma;
        public Firmalar FasonFirma
        {
            get { return fFasonFirma; }
            set { SetPropertyValue(nameof(FasonFirma), ref fFasonFirma, value); }
        }

        DateTime fGonderimTarihi;
        public DateTime GonderimTarihi
        {
            get { return fGonderimTarihi; }
            set { SetPropertyValue(nameof(GonderimTarihi), ref fGonderimTarihi, value); }
        }

        DateTime fTeslimTarihi;
        public DateTime TeslimTarihi
        {
            get { return fTeslimTarihi; }
            set { SetPropertyValue(nameof(TeslimTarihi), ref fTeslimTarihi, value); }
        }

        decimal fMaliyet;
        public decimal Maliyet
        {
            get { return fMaliyet; }
            set { SetPropertyValue(nameof(Maliyet), ref fMaliyet, value); }
        }

        decimal fAnlasilanFiyat;
        public decimal AnlasilanFiyat
        {
            get { return fAnlasilanFiyat; }
            set { SetPropertyValue(nameof(AnlasilanFiyat), ref fAnlasilanFiyat, value); }
        }
    }
}
