//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Faturalar : XPObject
    {
        string firsaliyeNo;
        public string irsaliyeNo
        {
            get { return firsaliyeNo; }
            set { SetPropertyValue<string>(nameof(irsaliyeNo), ref firsaliyeNo, value); }
        }
        Firmalar fFirma;
        public Firmalar Firma
        {
            get { return fFirma; }
            set { SetPropertyValue<Firmalar>(nameof(Firma), ref fFirma, value); }
        }
        string fFaturaNo;
        public string FaturaNo
        {
            get { return fFaturaNo; }
            set { SetPropertyValue<string>(nameof(FaturaNo), ref fFaturaNo, value); }
        }
        DateTime fFaturaTarihi;
        public DateTime FaturaTarihi
        {
            get { return fFaturaTarihi; }
            set { SetPropertyValue<DateTime>(nameof(FaturaTarihi), ref fFaturaTarihi, value); }
        }
        Parabirimi fF_ParaBirimi;
        public Parabirimi F_ParaBirimi
        {
            get { return fF_ParaBirimi; }
            set { SetPropertyValue<Parabirimi>(nameof(F_ParaBirimi), ref fF_ParaBirimi, value); }
        }
        decimal fDvz_Kuru;
        public decimal Dvz_Kuru
        {
            get { return fDvz_Kuru; }
            set { SetPropertyValue<decimal>(nameof(Dvz_Kuru), ref fDvz_Kuru, value); }
        }
        double fMal_Hizmet_ToplamDvz;
        public double Mal_Hizmet_ToplamDvz
        {
            get { return fMal_Hizmet_ToplamDvz; }
            set { SetPropertyValue<double>(nameof(Mal_Hizmet_ToplamDvz), ref fMal_Hizmet_ToplamDvz, value); }
        }
        double fMal_Hizmet_ToplamTL;
        public double Mal_Hizmet_ToplamTL
        {
            get { return fMal_Hizmet_ToplamTL; }
            set { SetPropertyValue<double>(nameof(Mal_Hizmet_ToplamTL), ref fMal_Hizmet_ToplamTL, value); }
        }
        int fKdvOranı;
        public int KdvOranı
        {
            get { return fKdvOranı; }
            set { SetPropertyValue<int>(nameof(KdvOranı), ref fKdvOranı, value); }
        }
        double fHesaplananKdvDvz;
        public double HesaplananKdvDvz
        {
            get { return fHesaplananKdvDvz; }
            set { SetPropertyValue<double>(nameof(HesaplananKdvDvz), ref fHesaplananKdvDvz, value); }
        }
        double fHesaplananKdvTL;
        public double HesaplananKdvTL
        {
            get { return fHesaplananKdvTL; }
            set { SetPropertyValue<double>(nameof(HesaplananKdvTL), ref fHesaplananKdvTL, value); }
        }
        double fVergiDahilTplmDvz;
        public double VergiDahilTplmDvz
        {
            get { return fVergiDahilTplmDvz; }
            set { SetPropertyValue<double>(nameof(VergiDahilTplmDvz), ref fVergiDahilTplmDvz, value); }
        }
        double fVergiDahilTplmTL;
        public double VergiDahilTplmTL
        {
            get { return fVergiDahilTplmTL; }
            set { SetPropertyValue<double>(nameof(VergiDahilTplmTL), ref fVergiDahilTplmTL, value); }
        }
        double fOdenecekTutar;
        public double OdenecekTutar
        {
            get { return fOdenecekTutar; }
            set { SetPropertyValue<double>(nameof(OdenecekTutar), ref fOdenecekTutar, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"FaturalarReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
        [Association(@"FaturaNotlarReferencesFaturalar")]
        public XPCollection<FaturaNotlar> FaturaNotlars { get { return GetCollection<FaturaNotlar>(nameof(FaturaNotlars)); } }
        [Association(@"irsaliyelerReferencesFaturalar")]
        public XPCollection<irsaliyeler> irsaliyelers { get { return GetCollection<irsaliyeler>(nameof(irsaliyelers)); } }
    }

}
