//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class FoyOdemePlani : XPObject
    {
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        OdemeSekilleri fOdemeSekli;
        public OdemeSekilleri OdemeSekli
        {
            get { return fOdemeSekli; }
            set { SetPropertyValue<OdemeSekilleri>(nameof(OdemeSekli), ref fOdemeSekli, value); }
        }
        DevExpress.Persistent.BaseImpl.FileData fBelge;
        public DevExpress.Persistent.BaseImpl.FileData Belge
        {
            get { return fBelge; }
            set { SetPropertyValue<DevExpress.Persistent.BaseImpl.FileData>(nameof(Belge), ref fBelge, value); }
        }
        decimal fTutar;
        public decimal Tutar
        {
            get { return fTutar; }
            set { SetPropertyValue<decimal>(nameof(Tutar), ref fTutar, value); }
        }
        SiparisFoy fSiparisFoy;
        [Association(@"FoyOdemePlaniReferencesSiparisFoy")]
        public SiparisFoy SiparisFoy
        {
            get { return fSiparisFoy; }
            set { SetPropertyValue<SiparisFoy>(nameof(SiparisFoy), ref fSiparisFoy, value); }
        }
        Kiralama_Satis fKiralamaSatis;
        [Association(@"FoyOdemePlaniReferencesKiralama_Satis")]
        public Kiralama_Satis KiralamaSatis
        {
            get { return fKiralamaSatis; }
            set { SetPropertyValue<Kiralama_Satis>(nameof(KiralamaSatis), ref fKiralamaSatis, value); }
        }
    }

}
