//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class GunlukKesim : XPObject
    {
        DateTime fKesimTarihi;
        public DateTime KesimTarihi
        {
            get { return fKesimTarihi; }
            set { SetPropertyValue<DateTime>(nameof(KesimTarihi), ref fKesimTarihi, value); }
        }
        irsaliyeler fKumasParti;
        public irsaliyeler KumasParti
        {
            get { return fKumasParti; }
            set { SetPropertyValue<irsaliyeler>(nameof(KumasParti), ref fKumasParti, value); }
        }
        decimal fPlanlanan_Gr_M2;
        public decimal Planlanan_Gr_M2
        {
            get { return fPlanlanan_Gr_M2; }
            set { SetPropertyValue<decimal>(nameof(Planlanan_Gr_M2), ref fPlanlanan_Gr_M2, value); }
        }
        int fEni;
        public int Eni
        {
            get { return fEni; }
            set { SetPropertyValue<int>(nameof(Eni), ref fEni, value); }
        }
        decimal fGelenKG;
        public decimal GelenKG
        {
            get { return fGelenKG; }
            set { SetPropertyValue<decimal>(nameof(GelenKG), ref fGelenKG, value); }
        }
        int fKesilenAdet;
        public int KesilenAdet
        {
            get { return fKesilenAdet; }
            set { SetPropertyValue<int>(nameof(KesilenAdet), ref fKesilenAdet, value); }
        }
        decimal fGerceklesen_Gr_M2;
        public decimal Gerceklesen_Gr_M2
        {
            get { return fGerceklesen_Gr_M2; }
            set { SetPropertyValue<decimal>(nameof(Gerceklesen_Gr_M2), ref fGerceklesen_Gr_M2, value); }
        }
        decimal fKalanKumas;
        public decimal KalanKumas
        {
            get { return fKalanKumas; }
            set { SetPropertyValue<decimal>(nameof(KalanKumas), ref fKalanKumas, value); }
        }
        decimal fTopBasi;
        public decimal TopBasi
        {
            get { return fTopBasi; }
            set { SetPropertyValue<decimal>(nameof(TopBasi), ref fTopBasi, value); }
        }
        decimal fKirpinti;
        public decimal Kirpinti
        {
            get { return fKirpinti; }
            set { SetPropertyValue<decimal>(nameof(Kirpinti), ref fKirpinti, value); }
        }
        decimal fBiye;
        public decimal Biye
        {
            get { return fBiye; }
            set { SetPropertyValue<decimal>(nameof(Biye), ref fBiye, value); }
        }
        decimal fTiriyajdaAyrilan;
        public decimal TiriyajdaAyrilan
        {
            get { return fTiriyajdaAyrilan; }
            set { SetPropertyValue<decimal>(nameof(TiriyajdaAyrilan), ref fTiriyajdaAyrilan, value); }
        }
        SiparisKarti fSiparisTo;
        [Association(@"GunlukKesimReferencesSiparisKarti")]
        public SiparisKarti SiparisTo
        {
            get { return fSiparisTo; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisTo), ref fSiparisTo, value); }
        }
        int fXXS;
        public int XXS
        {
            get { return fXXS; }
            set { SetPropertyValue<int>(nameof(XXS), ref fXXS, value); }
        }
        int fXS;
        public int XS
        {
            get { return fXS; }
            set { SetPropertyValue<int>(nameof(XS), ref fXS, value); }
        }
        int fS;
        public int S
        {
            get { return fS; }
            set { SetPropertyValue<int>(nameof(S), ref fS, value); }
        }
        int fM;
        public int M
        {
            get { return fM; }
            set { SetPropertyValue<int>(nameof(M), ref fM, value); }
        }
        int fL;
        public int L
        {
            get { return fL; }
            set { SetPropertyValue<int>(nameof(L), ref fL, value); }
        }
        int fXL;
        public int XL
        {
            get { return fXL; }
            set { SetPropertyValue<int>(nameof(XL), ref fXL, value); }
        }
        int fXXL;
        public int XXL
        {
            get { return fXXL; }
            set { SetPropertyValue<int>(nameof(XXL), ref fXXL, value); }
        }
        int fB3XL;
        public int B3XL
        {
            get { return fB3XL; }
            set { SetPropertyValue<int>(nameof(B3XL), ref fB3XL, value); }
        }
        int fB4XL;
        public int B4XL
        {
            get { return fB4XL; }
            set { SetPropertyValue<int>(nameof(B4XL), ref fB4XL, value); }
        }
        int fB5XL;
        public int B5XL
        {
            get { return fB5XL; }
            set { SetPropertyValue<int>(nameof(B5XL), ref fB5XL, value); }
        }
        int fB6XL;
        public int B6XL
        {
            get { return fB6XL; }
            set { SetPropertyValue<int>(nameof(B6XL), ref fB6XL, value); }
        }
        int fB4;
        public int B4
        {
            get { return fB4; }
            set { SetPropertyValue<int>(nameof(B4), ref fB4, value); }
        }
        int fB6;
        public int B6
        {
            get { return fB6; }
            set { SetPropertyValue<int>(nameof(B6), ref fB6, value); }
        }
        int fB8;
        public int B8
        {
            get { return fB8; }
            set { SetPropertyValue<int>(nameof(B8), ref fB8, value); }
        }
        int fB10;
        public int B10
        {
            get { return fB10; }
            set { SetPropertyValue<int>(nameof(B10), ref fB10, value); }
        }
        int fB12;
        public int B12
        {
            get { return fB12; }
            set { SetPropertyValue<int>(nameof(B12), ref fB12, value); }
        }
        int fB14;
        public int B14
        {
            get { return fB14; }
            set { SetPropertyValue<int>(nameof(B14), ref fB14, value); }
        }
        int fB16;
        public int B16
        {
            get { return fB16; }
            set { SetPropertyValue<int>(nameof(B16), ref fB16, value); }
        }
        int fB18;
        public int B18
        {
            get { return fB18; }
            set { SetPropertyValue<int>(nameof(B18), ref fB18, value); }
        }
        int fB20;
        public int B20
        {
            get { return fB20; }
            set { SetPropertyValue<int>(nameof(B20), ref fB20, value); }
        }
        int fB22;
        public int B22
        {
            get { return fB22; }
            set { SetPropertyValue<int>(nameof(B22), ref fB22, value); }
        }
        int fB24;
        public int B24
        {
            get { return fB24; }
            set { SetPropertyValue<int>(nameof(B24), ref fB24, value); }
        }
        int fB26;
        public int B26
        {
            get { return fB26; }
            set { SetPropertyValue<int>(nameof(B26), ref fB26, value); }
        }
        int fB28;
        public int B28
        {
            get { return fB28; }
            set { SetPropertyValue<int>(nameof(B28), ref fB28, value); }
        }
        int fB30;
        public int B30
        {
            get { return fB30; }
            set { SetPropertyValue<int>(nameof(B30), ref fB30, value); }
        }
        int fB32;
        public int B32
        {
            get { return fB32; }
            set { SetPropertyValue<int>(nameof(B32), ref fB32, value); }
        }
        int fB34;
        public int B34
        {
            get { return fB34; }
            set { SetPropertyValue<int>(nameof(B34), ref fB34, value); }
        }
        int fB36;
        public int B36
        {
            get { return fB36; }
            set { SetPropertyValue<int>(nameof(B36), ref fB36, value); }
        }
        int fY5_6;
        public int Y5_6
        {
            get { return fY5_6; }
            set { SetPropertyValue<int>(nameof(Y5_6), ref fY5_6, value); }
        }
        int fY7_8;
        public int Y7_8
        {
            get { return fY7_8; }
            set { SetPropertyValue<int>(nameof(Y7_8), ref fY7_8, value); }
        }
        int fY9_10;
        public int Y9_10
        {
            get { return fY9_10; }
            set { SetPropertyValue<int>(nameof(Y9_10), ref fY9_10, value); }
        }
        int fY11_12;
        public int Y11_12
        {
            get { return fY11_12; }
            set { SetPropertyValue<int>(nameof(Y11_12), ref fY11_12, value); }
        }
        int fY13;
        public int Y13
        {
            get { return fY13; }
            set { SetPropertyValue<int>(nameof(Y13), ref fY13, value); }
        }
        int fB56;
        public int B56
        {
            get { return fB56; }
            set { SetPropertyValue<int>(nameof(B56), ref fB56, value); }
        }
        int fB62;
        public int B62
        {
            get { return fB62; }
            set { SetPropertyValue<int>(nameof(B62), ref fB62, value); }
        }
        int fB68;
        public int B68
        {
            get { return fB68; }
            set { SetPropertyValue<int>(nameof(B68), ref fB68, value); }
        }
        int fB74;
        public int B74
        {
            get { return fB74; }
            set { SetPropertyValue<int>(nameof(B74), ref fB74, value); }
        }
        int fB80;
        public int B80
        {
            get { return fB80; }
            set { SetPropertyValue<int>(nameof(B80), ref fB80, value); }
        }
        int fB86;
        public int B86
        {
            get { return fB86; }
            set { SetPropertyValue<int>(nameof(B86), ref fB86, value); }
        }
        int fB92;
        public int B92
        {
            get { return fB92; }
            set { SetPropertyValue<int>(nameof(B92), ref fB92, value); }
        }
        int fB98;
        public int B98
        {
            get { return fB98; }
            set { SetPropertyValue<int>(nameof(B98), ref fB98, value); }
        }
        int fB104;
        public int B104
        {
            get { return fB104; }
            set { SetPropertyValue<int>(nameof(B104), ref fB104, value); }
        }
        int fB110;
        public int B110
        {
            get { return fB110; }
            set { SetPropertyValue<int>(nameof(B110), ref fB110, value); }
        }
        int fB116;
        public int B116
        {
            get { return fB116; }
            set { SetPropertyValue<int>(nameof(B116), ref fB116, value); }
        }
        int fB122;
        public int B122
        {
            get { return fB122; }
            set { SetPropertyValue<int>(nameof(B122), ref fB122, value); }
        }
        int fB128;
        public int B128
        {
            get { return fB128; }
            set { SetPropertyValue<int>(nameof(B128), ref fB128, value); }
        }
        int fB134;
        public int B134
        {
            get { return fB134; }
            set { SetPropertyValue<int>(nameof(B134), ref fB134, value); }
        }
        int fB140;
        public int B140
        {
            get { return fB140; }
            set { SetPropertyValue<int>(nameof(B140), ref fB140, value); }
        }
        int fB156;
        public int B156
        {
            get { return fB156; }
            set { SetPropertyValue<int>(nameof(B156), ref fB156, value); }
        }
        SiparisDetay fSiparisDetay_To;
        public SiparisDetay SiparisDetay_To
        {
            get { return fSiparisDetay_To; }
            set { SetPropertyValue<SiparisDetay>(nameof(SiparisDetay_To), ref fSiparisDetay_To, value); }
        }
        ModelBolge fParca;
        [MemberDesignTimeVisibility(true)]
        public ModelBolge Parca
        {
            get { return fParca; }
            set { SetPropertyValue<ModelBolge>(nameof(Parca), ref fParca, value); }
        }
    }

}
