//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class KaliteKontrolTest : XPObject
    {
        SiparisKarti fSiparisKarti;
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
        KumasKarti fKumasKarti;
        public KumasKarti KumasKarti
        {
            get { return fKumasKarti; }
            set { SetPropertyValue<KumasKarti>(nameof(KumasKarti), ref fKumasKarti, value); }
        }
        DateTime fTestBaslamaTarih;
        public DateTime TestBaslamaTarih
        {
            get { return fTestBaslamaTarih; }
            set { SetPropertyValue<DateTime>(nameof(TestBaslamaTarih), ref fTestBaslamaTarih, value); }
        }
        DateTime fSonuclanmaTarih;
        public DateTime SonuclanmaTarih
        {
            get { return fSonuclanmaTarih; }
            set { SetPropertyValue<DateTime>(nameof(SonuclanmaTarih), ref fSonuclanmaTarih, value); }
        }
        string fSonuc;
        public string Sonuc
        {
            get { return fSonuc; }
            set { SetPropertyValue<string>(nameof(Sonuc), ref fSonuc, value); }
        }
        string fTestiYapan;
        public string TestiYapan
        {
            get { return fTestiYapan; }
            set { SetPropertyValue<string>(nameof(TestiYapan), ref fTestiYapan, value); }
        }
    }

}
