//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class KdvOranlari : XPObject
    {
        decimal fKdv;
        public decimal Kdv
        {
            get { return fKdv; }
            set { SetPropertyValue<decimal>(nameof(Kdv), ref fKdv, value); }
        }
    }

}
