//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class KesimBeden : XPObject
    {
        DateTime fKesimTarihi;
        public DateTime KesimTarihi
        {
            get { return fKesimTarihi; }
            set { SetPropertyValue<DateTime>(nameof(KesimTarihi), ref fKesimTarihi, value); }
        }
        string fKesimNo;
        public string KesimNo
        {
            get { return fKesimNo; }
            set { SetPropertyValue<string>(nameof(KesimNo), ref fKesimNo, value); }
        }
        irsaliyeler fPartiNo;
        public irsaliyeler PartiNo
        {
            get { return fPartiNo; }
            set { SetPropertyValue<irsaliyeler>(nameof(PartiNo), ref fPartiNo, value); }
        }
        decimal fToplam;
        public decimal Toplam
        {
            get { return fToplam; }
            set { SetPropertyValue<decimal>(nameof(Toplam), ref fToplam, value); }
        }
        SiparisKarti fSiparisto;
        public SiparisKarti Siparisto
        {
            get { return fSiparisto; }
            set { SetPropertyValue<SiparisKarti>(nameof(Siparisto), ref fSiparisto, value); }
        }
        SiparisDetay fBedenler;
        public SiparisDetay Bedenler
        {
            get { return fBedenler; }
            set { SetPropertyValue<SiparisDetay>(nameof(Bedenler), ref fBedenler, value); }
        }
        int fGerceklesenGrmj_M2;
        public int GerceklesenGrmj_M2
        {
            get { return fGerceklesenGrmj_M2; }
            set { SetPropertyValue<int>(nameof(GerceklesenGrmj_M2), ref fGerceklesenGrmj_M2, value); }
        }
        int fKumasEn;
        public int KumasEn
        {
            get { return fKumasEn; }
            set { SetPropertyValue<int>(nameof(KumasEn), ref fKumasEn, value); }
        }
        decimal fGelenKG;
        public decimal GelenKG
        {
            get { return fGelenKG; }
            set { SetPropertyValue<decimal>(nameof(GelenKG), ref fGelenKG, value); }
        }
        int fGerceklesenGrmj;
        public int GerceklesenGrmj
        {
            get { return fGerceklesenGrmj; }
            set { SetPropertyValue<int>(nameof(GerceklesenGrmj), ref fGerceklesenGrmj, value); }
        }
        decimal fKalanKumas;
        public decimal KalanKumas
        {
            get { return fKalanKumas; }
            set { SetPropertyValue<decimal>(nameof(KalanKumas), ref fKalanKumas, value); }
        }
        decimal fTopBasi;
        public decimal TopBasi
        {
            get { return fTopBasi; }
            set { SetPropertyValue<decimal>(nameof(TopBasi), ref fTopBasi, value); }
        }
        decimal fKirpinti;
        public decimal Kirpinti
        {
            get { return fKirpinti; }
            set { SetPropertyValue<decimal>(nameof(Kirpinti), ref fKirpinti, value); }
        }
        decimal fBiye;
        public decimal Biye
        {
            get { return fBiye; }
            set { SetPropertyValue<decimal>(nameof(Biye), ref fBiye, value); }
        }
        decimal fTriyajdaAyrilan;
        public decimal TriyajdaAyrilan
        {
            get { return fTriyajdaAyrilan; }
            set { SetPropertyValue<decimal>(nameof(TriyajdaAyrilan), ref fTriyajdaAyrilan, value); }
        }
    }

}
