//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Kiralama_Satis : XPObject
    {
        Stoklar fGelinlik;
        public Stoklar Gelinlik
        {
            get { return fGelinlik; }
            set { SetPropertyValue<Stoklar>(nameof(Gelinlik), ref fGelinlik, value); }
        }
        string fMusteriAdi;
        public string MusteriAdi
        {
            get { return fMusteriAdi; }
            set { SetPropertyValue<string>(nameof(MusteriAdi), ref fMusteriAdi, value); }
        }
        string fTCNo;
        public string TCNo
        {
            get { return fTCNo; }
            set { SetPropertyValue<string>(nameof(TCNo), ref fTCNo, value); }
        }
        string fEposta;
        public string Eposta
        {
            get { return fEposta; }
            set { SetPropertyValue<string>(nameof(Eposta), ref fEposta, value); }
        }
        string fTelefonu;
        public string Telefonu
        {
            get { return fTelefonu; }
            set { SetPropertyValue<string>(nameof(Telefonu), ref fTelefonu, value); }
        }
        string fTelefon2;
        public string Telefon2
        {
            get { return fTelefon2; }
            set { SetPropertyValue<string>(nameof(Telefon2), ref fTelefon2, value); }
        }
        string fAdresi;
        [Size(SizeAttribute.Unlimited)]
        public string Adresi
        {
            get { return fAdresi; }
            set { SetPropertyValue<string>(nameof(Adresi), ref fAdresi, value); }
        }
        DateTime fGelinlikKTarihi;
        public DateTime GelinlikKTarihi
        {
            get { return fGelinlikKTarihi; }
            set { SetPropertyValue<DateTime>(nameof(GelinlikKTarihi), ref fGelinlikKTarihi, value); }
        }
        DateTime fGelinlikKBitisTarihi;
        public DateTime GelinlikKBitisTarihi
        {
            get { return fGelinlikKBitisTarihi; }
            set { SetPropertyValue<DateTime>(nameof(GelinlikKBitisTarihi), ref fGelinlikKBitisTarihi, value); }
        }
        DateTime fNisanlikKTarihi;
        public DateTime NisanlikKTarihi
        {
            get { return fNisanlikKTarihi; }
            set { SetPropertyValue<DateTime>(nameof(NisanlikKTarihi), ref fNisanlikKTarihi, value); }
        }
        string fAciklama;
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fKiralayanYetkili;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari KiralayanYetkili
        {
            get { return fKiralayanYetkili; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(KiralayanYetkili), ref fKiralayanYetkili, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fiadeAlanYetkili;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari iadeAlanYetkili
        {
            get { return fiadeAlanYetkili; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(iadeAlanYetkili), ref fiadeAlanYetkili, value); }
        }
        Stoklar fNisanlik;
        public Stoklar Nisanlik
        {
            get { return fNisanlik; }
            set { SetPropertyValue<Stoklar>(nameof(Nisanlik), ref fNisanlik, value); }
        }
        Stoklar fKinalik;
        public Stoklar Kinalik
        {
            get { return fKinalik; }
            set { SetPropertyValue<Stoklar>(nameof(Kinalik), ref fKinalik, value); }
        }
        DateTime fKinalikKTarihi;
        public DateTime KinalikKTarihi
        {
            get { return fKinalikKTarihi; }
            set { SetPropertyValue<DateTime>(nameof(KinalikKTarihi), ref fKinalikKTarihi, value); }
        }
        DateTime fNisanlikKBitisTarihi;
        public DateTime NisanlikKBitisTarihi
        {
            get { return fNisanlikKBitisTarihi; }
            set { SetPropertyValue<DateTime>(nameof(NisanlikKBitisTarihi), ref fNisanlikKBitisTarihi, value); }
        }
        DateTime fKinalikKBitisTarihi;
        public DateTime KinalikKBitisTarihi
        {
            get { return fKinalikKBitisTarihi; }
            set { SetPropertyValue<DateTime>(nameof(KinalikKBitisTarihi), ref fKinalikKBitisTarihi, value); }
        }
        string fKayitTarihi;
        public string KayitTarihi
        {
            get { return fKayitTarihi; }
            set { SetPropertyValue<string>(nameof(KayitTarihi), ref fKayitTarihi, value); }
        }
        string fTeslimAlinanTarih;
        public string TeslimAlinanTarih
        {
            get { return fTeslimAlinanTarih; }
            set { SetPropertyValue<string>(nameof(TeslimAlinanTarih), ref fTeslimAlinanTarih, value); }
        }
        decimal fGelinlikFiyat;
        public decimal GelinlikFiyat
        {
            get { return fGelinlikFiyat; }
            set { SetPropertyValue<decimal>(nameof(GelinlikFiyat), ref fGelinlikFiyat, value); }
        }
        decimal fNisanlikFiyat;
        public decimal NisanlikFiyat
        {
            get { return fNisanlikFiyat; }
            set { SetPropertyValue<decimal>(nameof(NisanlikFiyat), ref fNisanlikFiyat, value); }
        }
        decimal fKinalikFiyat;
        public decimal KinalikFiyat
        {
            get { return fKinalikFiyat; }
            set { SetPropertyValue<decimal>(nameof(KinalikFiyat), ref fKinalikFiyat, value); }
        }
        decimal fToplamFiyat;
        public decimal ToplamFiyat
        {
            get { return fToplamFiyat; }
            set { SetPropertyValue<decimal>(nameof(ToplamFiyat), ref fToplamFiyat, value); }
        }
        bool fKiralik;
        public bool Kiralik
        {
            get { return fKiralik; }
            set { SetPropertyValue<bool>(nameof(Kiralik), ref fKiralik, value); }
        }
        bool fSatilik;
        public bool Satilik
        {
            get { return fSatilik; }
            set { SetPropertyValue<bool>(nameof(Satilik), ref fSatilik, value); }
        }
        bool fTac;
        public bool Tac
        {
            get { return fTac; }
            set { SetPropertyValue<bool>(nameof(Tac), ref fTac, value); }
        }
        decimal fTacFiyat;
        public decimal TacFiyat
        {
            get { return fTacFiyat; }
            set { SetPropertyValue<decimal>(nameof(TacFiyat), ref fTacFiyat, value); }
        }
        bool fDuvak;
        public bool Duvak
        {
            get { return fDuvak; }
            set { SetPropertyValue<bool>(nameof(Duvak), ref fDuvak, value); }
        }
        decimal fDuvakFiyat;
        public decimal DuvakFiyat
        {
            get { return fDuvakFiyat; }
            set { SetPropertyValue<decimal>(nameof(DuvakFiyat), ref fDuvakFiyat, value); }
        }
        bool fCicek;
        public bool Cicek
        {
            get { return fCicek; }
            set { SetPropertyValue<bool>(nameof(Cicek), ref fCicek, value); }
        }
        decimal fCicekFiyat;
        public decimal CicekFiyat
        {
            get { return fCicekFiyat; }
            set { SetPropertyValue<decimal>(nameof(CicekFiyat), ref fCicekFiyat, value); }
        }
        bool fHayalTul;
        public bool HayalTul
        {
            get { return fHayalTul; }
            set { SetPropertyValue<bool>(nameof(HayalTul), ref fHayalTul, value); }
        }
        decimal fHayalTulFiyat;
        public decimal HayalTulFiyat
        {
            get { return fHayalTulFiyat; }
            set { SetPropertyValue<decimal>(nameof(HayalTulFiyat), ref fHayalTulFiyat, value); }
        }
        [Association(@"KuaforTablosuReferencesKiralama_Satis"), Aggregated]
        public XPCollection<KuaforTablosu> KuaforTablosus { get { return GetCollection<KuaforTablosu>(nameof(KuaforTablosus)); } }
        [Association(@"ProvaTakipReferencesKiralama_Satis"), Aggregated]
        public XPCollection<ProvaTakip> ProvaTakips { get { return GetCollection<ProvaTakip>(nameof(ProvaTakips)); } }
        [Association(@"FoyOdemePlaniReferencesKiralama_Satis"), Aggregated]
        public XPCollection<FoyOdemePlani> FoyOdemePlanis { get { return GetCollection<FoyOdemePlani>(nameof(FoyOdemePlanis)); } }
    }

}
