//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class KumasTestDetay : XPObject
    {
        int fTopNo;
        public int TopNo
        {
            get { return fTopNo; }
            set { SetPropertyValue<int>(nameof(TopNo), ref fTopNo, value); }
        }
        double fKG;
        public double KG
        {
            get { return fKG; }
            set { SetPropertyValue<double>(nameof(KG), ref fKG, value); }
        }
        string fBoyaKirigi;
        public string BoyaKirigi
        {
            get { return fBoyaKirigi; }
            set { SetPropertyValue<string>(nameof(BoyaKirigi), ref fBoyaKirigi, value); }
        }
        string fLeke;
        public string Leke
        {
            get { return fLeke; }
            set { SetPropertyValue<string>(nameof(Leke), ref fLeke, value); }
        }
        string fUcuntu;
        public string Ucuntu
        {
            get { return fUcuntu; }
            set { SetPropertyValue<string>(nameof(Ucuntu), ref fUcuntu, value); }
        }
        string fSanforKirigi;
        public string SanforKirigi
        {
            get { return fSanforKirigi; }
            set { SetPropertyValue<string>(nameof(SanforKirigi), ref fSanforKirigi, value); }
        }
        string fLycraKacigi;
        public string LycraKacigi
        {
            get { return fLycraKacigi; }
            set { SetPropertyValue<string>(nameof(LycraKacigi), ref fLycraKacigi, value); }
        }
        string figneKirigi;
        public string igneKirigi
        {
            get { return figneKirigi; }
            set { SetPropertyValue<string>(nameof(igneKirigi), ref figneKirigi, value); }
        }
        string fSanforDurmaizi;
        public string SanforDurmaizi
        {
            get { return fSanforDurmaizi; }
            set { SetPropertyValue<string>(nameof(SanforDurmaizi), ref fSanforDurmaizi, value); }
        }
        string fPalamut;
        public string Palamut
        {
            get { return fPalamut; }
            set { SetPropertyValue<string>(nameof(Palamut), ref fPalamut, value); }
        }
        string fYirtik;
        public string Yirtik
        {
            get { return fYirtik; }
            set { SetPropertyValue<string>(nameof(Yirtik), ref fYirtik, value); }
        }
        string filmekKacigi;
        public string ilmekKacigi
        {
            get { return filmekKacigi; }
            set { SetPropertyValue<string>(nameof(ilmekKacigi), ref filmekKacigi, value); }
        }
        string fiplikAbraji;
        public string iplikAbraji
        {
            get { return fiplikAbraji; }
            set { SetPropertyValue<string>(nameof(iplikAbraji), ref fiplikAbraji, value); }
        }
        string fGramajDeligi;
        public string GramajDeligi
        {
            get { return fGramajDeligi; }
            set { SetPropertyValue<string>(nameof(GramajDeligi), ref fGramajDeligi, value); }
        }
        string fEkDikis;
        public string EkDikis
        {
            get { return fEkDikis; }
            set { SetPropertyValue<string>(nameof(EkDikis), ref fEkDikis, value); }
        }
        string fDelik;
        public string Delik
        {
            get { return fDelik; }
            set { SetPropertyValue<string>(nameof(Delik), ref fDelik, value); }
        }
        string fSilikon;
        public string Silikon
        {
            get { return fSilikon; }
            set { SetPropertyValue<string>(nameof(Silikon), ref fSilikon, value); }
        }
        irsaliyeler fKumasirsaliye;
        public irsaliyeler Kumasirsaliye
        {
            get { return fKumasirsaliye; }
            set { SetPropertyValue<irsaliyeler>(nameof(Kumasirsaliye), ref fKumasirsaliye, value); }
        }
        KumasTestOnaylayan fTestOnaylayan;
        public KumasTestOnaylayan TestOnaylayan
        {
            get { return fTestOnaylayan; }
            set { SetPropertyValue<KumasTestOnaylayan>(nameof(TestOnaylayan), ref fTestOnaylayan, value); }
        }
        Kumas_SatinAlma fKumasSatinAlma;
        [Association(@"KumasTestDetayReferencesKumas_SatinAlma")]
        public Kumas_SatinAlma KumasSatinAlma
        {
            get { return fKumasSatinAlma; }
            set { SetPropertyValue<Kumas_SatinAlma>(nameof(KumasSatinAlma), ref fKumasSatinAlma, value); }
        }
    }

}
