//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Kumas_iplikNo : XPObject
    {
        string fiplik_No;
        public string iplik_No
        {
            get { return fiplik_No; }
            set { SetPropertyValue<string>(nameof(iplik_No), ref fiplik_No, value); }
        }
    }

}
