//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class MaliyetMalzeme : XPObject
    {
        Model_Maliyet fModelMaliyet;
        [Association(@"MaliyetMalzemeReferencesModel_Maliyet")]
        public Model_Maliyet ModelMaliyet
        {
            get { return fModelMaliyet; }
            set { SetPropertyValue<Model_Maliyet>(nameof(ModelMaliyet), ref fModelMaliyet, value); }
        }
        MaliyetMalzemeleri fMalzeme;
        public MaliyetMalzemeleri Malzeme
        {
            get { return fMalzeme; }
            set { SetPropertyValue<MaliyetMalzemeleri>(nameof(Malzeme), ref fMalzeme, value); }
        }
        int fMiktar;
        public int Miktar
        {
            get { return fMiktar; }
            set { SetPropertyValue<int>(nameof(Miktar), ref fMiktar, value); }
        }
        Birim fBirim;
        public Birim Birim
        {
            get { return fBirim; }
            set { SetPropertyValue<Birim>(nameof(Birim), ref fBirim, value); }
        }
        Parabirimi fParaBirimi;
        public Parabirimi ParaBirimi
        {
            get { return fParaBirimi; }
            set { SetPropertyValue<Parabirimi>(nameof(ParaBirimi), ref fParaBirimi, value); }
        }
        double fBirimFiyatDoviz;
        public double BirimFiyatDoviz
        {
            get { return fBirimFiyatDoviz; }
            set { SetPropertyValue<double>(nameof(BirimFiyatDoviz), ref fBirimFiyatDoviz, value); }
        }
        double fBirimFiyatTL;
        public double BirimFiyatTL
        {
            get { return fBirimFiyatTL; }
            set { SetPropertyValue<double>(nameof(BirimFiyatTL), ref fBirimFiyatTL, value); }
        }
        double fToplamDoviz;
        public double ToplamDoviz
        {
            get { return fToplamDoviz; }
            set { SetPropertyValue<double>(nameof(ToplamDoviz), ref fToplamDoviz, value); }
        }
        double fToplamTL;
        public double ToplamTL
        {
            get { return fToplamTL; }
            set { SetPropertyValue<double>(nameof(ToplamTL), ref fToplamTL, value); }
        }
        string fAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
    }

}
