//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class MalzemeStok : XPObject
    {
        MaliyetMalzemeleri fMalzeme;
        public MaliyetMalzemeleri Malzeme
        {
            get { return fMalzeme; }
            set { SetPropertyValue(nameof(Malzeme), ref fMalzeme, value); }
        }

        double fStok;
        public double Stok
        {
            get { return fStok; }
            set { SetPropertyValue(nameof(Stok), ref fStok, value); }
        }

        DepoKart fDepo;
        public DepoKart Depo
        {
            get { return fDepo; }
            set { SetPropertyValue(nameof(Depo), ref fDepo, value); }
        }
    }
}
