//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Malzeme_SatinAlma : XPObject
    {
        SiparisKarti fSiparisKarti;
        [Association("SiparisKarti-Malzeme_SatinAlma")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }

        MaliyetMalzemeleri fMalzeme;
        public MaliyetMalzemeleri Malzeme
        {
            get { return fMalzeme; }
            set { SetPropertyValue(nameof(Malzeme), ref fMalzeme, value); }
        }

        double fGelenMiktar;
        public double GelenMiktar
        {
            get { return fGelenMiktar; }
            set { SetPropertyValue(nameof(GelenMiktar), ref fGelenMiktar, value); }
        }

        DepoKart fDepo;
        public DepoKart Depo
        {
            get { return fDepo; }
            set { SetPropertyValue(nameof(Depo), ref fDepo, value); }
        }
    }
}
