//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    public enum IslemYeri
    {
        FirmaIci,
        Fason
    }

    public partial class ModelOperasyon : XPObject
    {
        ModelKarti fModelKarti;
        [Association(@"ModelOperasyonReferencesModelKarti")]
        public ModelKarti ModelKarti
        {
            get { return fModelKarti; }
            set { SetPropertyValue<ModelKarti>(nameof(ModelKarti), ref fModelKarti, value); }
        }
        int fislemSirasi;
        public int islemSirasi
        {
            get { return fislemSirasi; }
            set { SetPropertyValue<int>(nameof(islemSirasi), ref fislemSirasi, value); }
        }

        int fParalelGrup;
        public int ParalelGrup
        {
            get { return fParalelGrup; }
            set { SetPropertyValue<int>(nameof(ParalelGrup), ref fParalelGrup, value); }
        }

        IslemYeri fIslemYeri;
        public IslemYeri IslemYeri
        {
            get { return fIslemYeri; }
            set { SetPropertyValue<IslemYeri>(nameof(IslemYeri), ref fIslemYeri, value); }
        }

        Makinalar fMakina;
        public Makinalar Makina
        {
            get { return fMakina; }
            set { SetPropertyValue<Makinalar>(nameof(Makina), ref fMakina, value); }
        }
        Operasyonlar fOperasyon;
        public Operasyonlar Operasyon
        {
            get { return fOperasyon; }
            set { SetPropertyValue<Operasyonlar>(nameof(Operasyon), ref fOperasyon, value); }
        }
        decimal fSure;
        public decimal Sure
        {
            get { return fSure; }
            set { SetPropertyValue<decimal>(nameof(Sure), ref fSure, value); }
        }
    }

}
