//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class ModeliscilikFiyatlandirma : XPObject
    {
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        ModelGrubu fModelGrubu;
        public ModelGrubu ModelGrubu
        {
            get { return fModelGrubu; }
            set { SetPropertyValue<ModelGrubu>(nameof(ModelGrubu), ref fModelGrubu, value); }
        }
        decimal fFiyat;
        public decimal Fiyat
        {
            get { return fFiyat; }
            set { SetPropertyValue<decimal>(nameof(Fiyat), ref fFiyat, value); }
        }
        string fAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
    }

}
