//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    public enum DestekTalebiDurumu { Acik, Cevaplandi, Kapandi }

    [DefaultClassOptions]
    [NavigationItem("Portal Yönetimi")]
    public partial class MusteriDestekTalebi : XPObject
    {
        public MusteriDestekTalebi(Session session) : base(session) { }

        Musteriler fMusteri;
        [Association("Musteri-DestekTalepleri")]
        public Musteriler Musteri
        {
            get { return fMusteri; }
            set { SetPropertyValue(nameof(Musteri), ref fMusteri, value); }
        }

        SiparisKarti fIlgiliSiparis;
        public SiparisKarti IlgiliSiparis
        {
            get { return fIlgiliSiparis; }
            set { SetPropertyValue(nameof(IlgiliSiparis), ref fIlgiliSiparis, value); }
        }

        string fKonu;
        public string Konu
        {
            get { return fKonu; }
            set { SetPropertyValue(nameof(Konu), ref fKonu, value); }
        }

        DateTime fOlusturmaTarihi;
        public DateTime OlusturmaTarihi
        {
            get { return fOlusturmaTarihi; }
            set { SetPropertyValue(nameof(OlusturmaTarihi), ref fOlusturmaTarihi, value); }
        }

        DestekTalebiDurumu fDurum;
        public DestekTalebiDurumu Durum
        {
            get { return fDurum; }
            set { SetPropertyValue(nameof(Durum), ref fDurum, value); }
        }

        [Association("DestekTalebi-Mesajlar"), DevExpress.Xpo.Aggregated]
        public XPCollection<DestekMesaji> Mesajlar
        {
            get { return GetCollection<DestekMesaji>(nameof(Mesajlar)); }
        }
    }
}
