//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Musteriler : XPObject
    {
        string fCariKodu;
        public string CariKodu
        {
            get { return fCariKodu; }
            set { SetPropertyValue<string>(nameof(CariKodu), ref fCariKodu, value); }
        }
        string fMusteriAdi;
        public string MusteriAdi
        {
            get { return fMusteriAdi; }
            set { SetPropertyValue<string>(nameof(MusteriAdi), ref fMusteriAdi, value); }
        }
        bool fYabanciMusteri;
        public bool YabanciMusteri
        {
            get { return fYabanciMusteri; }
            set { SetPropertyValue<bool>(nameof(YabanciMusteri), ref fYabanciMusteri, value); }
        }
        [Association(@"SiparisFoyReferencesMusteriler"), Aggregated]
        public XPCollection<SiparisFoy> SiparisFoys { get { return GetCollection<SiparisFoy>(nameof(SiparisFoys)); } }
        [Association(@"SubelerReferencesMusteriler"), Aggregated]
        public XPCollection<Subeler> Subelers { get { return GetCollection<Subeler>(nameof(Subelers)); } }
    }

}
