//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.BaseImpl.PermissionPolicy;
using DevExpress.Persistent.Base;

namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    [DefaultClassOptions]
    [NavigationItem("Portal Yönetimi")]
    public partial class PortalUserRole : PermissionPolicyRole
    {
        public PortalUserRole(Session session) : base(session) { }

        public override void AfterConstruction()
        {
            base.AfterConstruction();
            this.Name = "Portal Kullanıcısı";
            this.IsAdministrative = false;
        }
    }
}
