//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.BaseImpl.PermissionPolicy;
using DevExpress.Persistent.Base;

namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    [DefaultClassOptions]
    [NavigationItem("Portal Yönetimi")]
    public partial class PortalUser : PermissionPolicyUser
    {
        public PortalUser(Session session) : base(session) { }

        Musteriler fMusteri;
        [Association("Musteri-PortalKullanicilari")]
        public Musteriler Musteri
        {
            get { return fMusteri; }
            set { SetPropertyValue(nameof(Musteri), ref fMusteri, value); }
        }
    }
}
