//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    [DefaultClassOptions]
    public partial class ProvaResim : XPObject
    {
        ProvaDetay fProvaDetay;
        [Association(@"ProvaDetayReferencesProvaResim")]
        public ProvaDetay ProvaDetay
        {
            get { return fProvaDetay; }
            set { SetPropertyValue<ProvaDetay>(nameof(ProvaDetay), ref fProvaDetay, value); }
        }
        byte[] fResim;
        [Size(SizeAttribute.Unlimited)]
        [ImageEditor(ListViewImageEditorMode = ImageEditorMode.PictureEdit, DetailViewImageEditorMode = ImageEditorMode.PictureEdit)]
        public byte[] Resim
        {
            get { return fResim; }
            set { SetPropertyValue<byte[]>(nameof(Resim), ref fResim, value); }
        }
        string fAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
    }

}
