//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class ProvaDetay : XPObject
    {
        ProvaTakip fProvaTakip;
        [Association(@"ProvaDetayReferencesProvaTakip")]
        public ProvaTakip ProvaTakip
        {
            get { return fProvaTakip; }
            set { SetPropertyValue<ProvaTakip>(nameof(ProvaTakip), ref fProvaTakip, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fTemsilci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari Temsilci
        {
            get { return fTemsilci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(Temsilci), ref fTemsilci, value); }
        }

        // Ölçü alanları double olarak güncellendi
        double fOMUZBOY;
        public double OMUZBOY
        {
            get { return fOMUZBOY; }
            set { SetPropertyValue<double>(nameof(OMUZBOY), ref fOMUZBOY, value); }
        }
        double fGOGUS;
        public double GOGUS
        {
            get { return fGOGUS; }
            set { SetPropertyValue<double>(nameof(GOGUS), ref fGOGUS, value); }
        }
        double fBEL;
        public double BEL
        {
            get { return fBEL; }
            set { SetPropertyValue<double>(nameof(BEL), ref fBEL, value); }
        }
        double fBASEN;
        public double BASEN
        {
            get { return fBASEN; }
            set { SetPropertyValue<double>(nameof(BASEN), ref fBASEN, value); }
        }
        double fGOGUSDUS;
        public double GOGUSDUS
        {
            get { return fGOGUSDUS; }
            set { SetPropertyValue<double>(nameof(GOGUSDUS), ref fGOGUSDUS, value); }
        }
        double fONBEDENBOYU;
        public double ONBEDENBOYU
        {
            get { return fONBEDENBOYU; }
            set { SetPropertyValue<double>(nameof(ONBEDENBOYU), ref fONBEDENBOYU, value); }
        }
        double fARKAYAKADUS;
        public double ARKAYAKADUS
        {
            get { return fARKAYAKADUS; }
            set { SetPropertyValue<double>(nameof(ARKAYAKADUS), ref fARKAYAKADUS, value); }
        }
        double fDISOMUZ;
        public double DISOMUZ
        {
            get { return fDISOMUZ; }
            set { SetPropertyValue<double>(nameof(DISOMUZ), ref fDISOMUZ, value); }
        }
        double fOMUZ;
        public double OMUZ
        {
            get { return fOMUZ; }
            set { SetPropertyValue<double>(nameof(OMUZ), ref fOMUZ, value); }
        }
        double fYAKADUS;
        public double YAKADUS
        {
            get { return fYAKADUS; }
            set { SetPropertyValue<double>(nameof(YAKADUS), ref fYAKADUS, value); }
        }
        double fKOLBOYU;
        public double KOLBOYU
        {
            get { return fKOLBOYU; }
            set { SetPropertyValue<double>(nameof(KOLBOYU), ref fKOLBOYU, value); }
        }
        double fBILEK;
        public double BILEK
        {
            get { return fBILEK; }
            set { SetPropertyValue<double>(nameof(BILEK), ref fBILEK, value); }
        }
        double fPAZU;
        public double PAZU
        {
            get { return fPAZU; }
            set { SetPropertyValue<double>(nameof(PAZU), ref fPAZU, value); }
        }

        // Yeni alanlar eklendi
        string fYapilanDuzeltmeler;
        [Size(SizeAttribute.Unlimited)]
        public string YapilanDuzeltmeler
        {
            get { return fYapilanDuzeltmeler; }
            set { SetPropertyValue<string>(nameof(YapilanDuzeltmeler), ref fYapilanDuzeltmeler, value); }
        }
        string fProvaNotlari;
        [Size(SizeAttribute.Unlimited)]
        public string ProvaNotlari
        {
            get { return fProvaNotlari; }
            set { SetPropertyValue<string>(nameof(ProvaNotlari), ref fProvaNotlari, value); }
        }

        // Üretim entegrasyonu için SiparisOperasyon referansı
        SiparisOperasyon fIlgiliOperasyon;
        public SiparisOperasyon IlgiliOperasyon
        {
            get { return fIlgiliOperasyon; }
            set { SetPropertyValue<SiparisOperasyon>(nameof(IlgiliOperasyon), ref fIlgiliOperasyon, value); }
        }

        // Prova resimleri koleksiyonu
        [Association(@"ProvaDetayReferencesProvaResim"), DevExpress.Xpo.Aggregated]
        public XPCollection<ProvaResim> ProvaResimleri
        {
            get { return GetCollection<ProvaResim>(nameof(ProvaResimleri)); }
        }
    }

}
