//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Base.General;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    [DefaultClassOptions]
    [NavigationItem("Prova Yönetimi")]
    public partial class ProvaRandevu : XPObject, IEvent
    {
        public ProvaRandevu(Session session) : base(session) { }

        SiparisKarti fSiparisKarti;
        [Association("SiparisKarti-ProvaRandevulari")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }

        DateTime fStartTime;
        public DateTime StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue(nameof(StartTime), ref fStartTime, value); }
        }

        DateTime fEndTime;
        public DateTime EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue(nameof(EndTime), ref fEndTime, value); }
        }

        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue(nameof(Subject), ref fSubject, value); }
        }

        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue(nameof(Description), ref fDescription, value); }
        }

        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue(nameof(Location), ref fLocation, value); }
        }

        bool fAllDay;
        public bool AllDay
        {
            get { return fAllDay; }
            set { SetPropertyValue(nameof(AllDay), ref fAllDay, value); }
        }

        int fLabel;
        public int Label
        {
            get { return fLabel; }
            set { SetPropertyValue(nameof(Label), ref fLabel, value); }
        }

        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue(nameof(Status), ref fStatus, value); }
        }

        #region IEvent Members
        [Browsable(false)]
        public object AppointmentId => Oid;

        [Browsable(false)]
        public DateTime StartOn => StartTime;

        [Browsable(false)]
        public DateTime EndOn => EndTime;

        #endregion
    }
}
