//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class ProvaDetay : XPObject
    {
        ProvaTakip fProvaTakip;
        [Association(@"ProvaDetayReferencesProvaTakip")]
        public ProvaTakip ProvaTakip
        {
            get { return fProvaTakip; }
            set { SetPropertyValue<ProvaTakip>(nameof(ProvaTakip), ref fProvaTakip, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fTemsilci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari Temsilci
        {
            get { return fTemsilci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(Temsilci), ref fTemsilci, value); }
        }
        string fOMUZBOY;
        public string OMUZBOY
        {
            get { return fOMUZBOY; }
            set { SetPropertyValue<string>(nameof(OMUZBOY), ref fOMUZBOY, value); }
        }
        string fGOGUS;
        public string GOGUS
        {
            get { return fGOGUS; }
            set { SetPropertyValue<string>(nameof(GOGUS), ref fGOGUS, value); }
        }
        string fBEL;
        public string BEL
        {
            get { return fBEL; }
            set { SetPropertyValue<string>(nameof(BEL), ref fBEL, value); }
        }
        string fBASEN;
        public string BASEN
        {
            get { return fBASEN; }
            set { SetPropertyValue<string>(nameof(BASEN), ref fBASEN, value); }
        }
        string fGOGUSDUS;
        public string GOGUSDUS
        {
            get { return fGOGUSDUS; }
            set { SetPropertyValue<string>(nameof(GOGUSDUS), ref fGOGUSDUS, value); }
        }
        string fONBEDENBOYU;
        public string ONBEDENBOYU
        {
            get { return fONBEDENBOYU; }
            set { SetPropertyValue<string>(nameof(ONBEDENBOYU), ref fONBEDENBOYU, value); }
        }
        string fARKAYAKADUS;
        public string ARKAYAKADUS
        {
            get { return fARKAYAKADUS; }
            set { SetPropertyValue<string>(nameof(ARKAYAKADUS), ref fARKAYAKADUS, value); }
        }
        string fDISOMUZ;
        public string DISOMUZ
        {
            get { return fDISOMUZ; }
            set { SetPropertyValue<string>(nameof(DISOMUZ), ref fDISOMUZ, value); }
        }
        string fOMUZ;
        public string OMUZ
        {
            get { return fOMUZ; }
            set { SetPropertyValue<string>(nameof(OMUZ), ref fOMUZ, value); }
        }
        string fYAKADUS;
        public string YAKADUS
        {
            get { return fYAKADUS; }
            set { SetPropertyValue<string>(nameof(YAKADUS), ref fYAKADUS, value); }
        }
        string fKOLBOYU;
        public string KOLBOYU
        {
            get { return fKOLBOYU; }
            set { SetPropertyValue<string>(nameof(KOLBOYU), ref fKOLBOYU, value); }
        }
        string fBILEK;
        public string BILEK
        {
            get { return fBILEK; }
            set { SetPropertyValue<string>(nameof(BILEK), ref fBILEK, value); }
        }
        string fPAZU;
        public string PAZU
        {
            get { return fPAZU; }
            set { SetPropertyValue<string>(nameof(PAZU), ref fPAZU, value); }
        }
        string fACIKLAMA;
        public string ACIKLAMA
        {
            get { return fACIKLAMA; }
            set { SetPropertyValue<string>(nameof(ACIKLAMA), ref fACIKLAMA, value); }
        }
    }

}
