//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    public enum TeslimatDurumu
    {
        Hazirlaniyor,
        Yolda,
        TeslimEdildi
    }

    public partial class Sevkiyat : XPObject
    {
        SiparisKarti fSiparisKarti;
        [Association("SiparisKarti-Sevkiyat")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }

        string fKargoFirmasi;
        public string KargoFirmasi
        {
            get { return fKargoFirmasi; }
            set { SetPropertyValue(nameof(KargoFirmasi), ref fKargoFirmasi, value); }
        }

        string fTakipNumarasi;
        public string TakipNumarasi
        {
            get { return fTakipNumarasi; }
            set { SetPropertyValue(nameof(TakipNumarasi), ref fTakipNumarasi, value); }
        }

        DateTime fSevkiyatTarihi;
        public DateTime SevkiyatTarihi
        {
            get { return fSevkiyatTarihi; }
            set { SetPropertyValue(nameof(SevkiyatTarihi), ref fSevkiyatTarihi, value); }
        }

        TeslimatDurumu fTeslimatDurumu;
        public TeslimatDurumu TeslimatDurumu
        {
            get { return fTeslimatDurumu; }
            set { SetPropertyValue(nameof(TeslimatDurumu), ref fTeslimatDurumu, value); }
        }
    }
}
