//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class SiparisKesimTablosu : XPObject
    {
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fAltKesimci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari AltKesimci
        {
            get { return fAltKesimci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(AltKesimci), ref fAltKesimci, value); }
        }
        DateTime fAltKesimTarihi;
        public DateTime AltKesimTarihi
        {
            get { return fAltKesimTarihi; }
            set { SetPropertyValue<DateTime>(nameof(AltKesimTarihi), ref fAltKesimTarihi, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fUstKesimci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari UstKesimci
        {
            get { return fUstKesimci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(UstKesimci), ref fUstKesimci, value); }
        }
        DateTime fUstKesimTarihi;
        public DateTime UstKesimTarihi
        {
            get { return fUstKesimTarihi; }
            set { SetPropertyValue<DateTime>(nameof(UstKesimTarihi), ref fUstKesimTarihi, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"SiparisKesimTablosuReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
    }

}
