//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Siparisislemler : XPObject
    {
        ModelMaliyetislem fislemTuru;
        public ModelMaliyetislem islemTuru
        {
            get { return fislemTuru; }
            set { SetPropertyValue<ModelMaliyetislem>(nameof(islemTuru), ref fislemTuru, value); }
        }
        ModelBolge fBolge;
        public ModelBolge Bolge
        {
            get { return fBolge; }
            set { SetPropertyValue<ModelBolge>(nameof(Bolge), ref fBolge, value); }
        }
        byte[] fResim;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    ListViewImageEditorCustomHeight = 40)]
        public byte[] Resim
        {
            get { return fResim; }
            set { SetPropertyValue<byte[]>(nameof(Resim), ref fResim, value); }
        }
        string fAciklama;
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"SiparisislemlerReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
        double fMiktar;
        public double Miktar
        {
            get { return fMiktar; }
            set { SetPropertyValue<double>(nameof(Miktar), ref fMiktar, value); }
        }
        Birim fBirim;
        public Birim Birim
        {
            get { return fBirim; }
            set { SetPropertyValue<Birim>(nameof(Birim), ref fBirim, value); }
        }
        string fFireOran;
        public string FireOran
        {
            get { return fFireOran; }
            set { SetPropertyValue<string>(nameof(FireOran), ref fFireOran, value); }
        }
        double fPlanlanan;
        public double Planlanan
        {
            get { return fPlanlanan; }
            set { SetPropertyValue<double>(nameof(Planlanan), ref fPlanlanan, value); }
        }
        int fTemsilciAciklama;
        public int TemsilciAciklama
        {
            get { return fTemsilciAciklama; }
            set { SetPropertyValue<int>(nameof(TemsilciAciklama), ref fTemsilciAciklama, value); }
        }
        double fMaliyetFiyat;
        public double MaliyetFiyat
        {
            get { return fMaliyetFiyat; }
            set { SetPropertyValue<double>(nameof(MaliyetFiyat), ref fMaliyetFiyat, value); }
        }
        Parabirimi fM_ParaBirimi;
        public Parabirimi M_ParaBirimi
        {
            get { return fM_ParaBirimi; }
            set { SetPropertyValue<Parabirimi>(nameof(M_ParaBirimi), ref fM_ParaBirimi, value); }
        }
        DateTime fM_Kur_Tarih;
        public DateTime M_Kur_Tarih
        {
            get { return fM_Kur_Tarih; }
            set { SetPropertyValue<DateTime>(nameof(M_Kur_Tarih), ref fM_Kur_Tarih, value); }
        }
        double fM_Tplm_Dvz;
        public double M_Tplm_Dvz
        {
            get { return fM_Tplm_Dvz; }
            set { SetPropertyValue<double>(nameof(M_Tplm_Dvz), ref fM_Tplm_Dvz, value); }
        }
        decimal fM_Kuru;
        public decimal M_Kuru
        {
            get { return fM_Kuru; }
            set { SetPropertyValue<decimal>(nameof(M_Kuru), ref fM_Kuru, value); }
        }
        double fM_Tplm_TL;
        public double M_Tplm_TL
        {
            get { return fM_Tplm_TL; }
            set { SetPropertyValue<double>(nameof(M_Tplm_TL), ref fM_Tplm_TL, value); }
        }
        string fTalepNo;
        public string TalepNo
        {
            get { return fTalepNo; }
            set { SetPropertyValue<string>(nameof(TalepNo), ref fTalepNo, value); }
        }
        DateTime fTerminTarihi;
        public DateTime TerminTarihi
        {
            get { return fTerminTarihi; }
            set { SetPropertyValue<DateTime>(nameof(TerminTarihi), ref fTerminTarihi, value); }
        }
        DateTime fSiparisYadaGonderimTarih;
        public DateTime SiparisYadaGonderimTarih
        {
            get { return fSiparisYadaGonderimTarih; }
            set { SetPropertyValue<DateTime>(nameof(SiparisYadaGonderimTarih), ref fSiparisYadaGonderimTarih, value); }
        }
        int fSiparisYadaGonderilenAdet;
        public int SiparisYadaGonderilenAdet
        {
            get { return fSiparisYadaGonderilenAdet; }
            set { SetPropertyValue<int>(nameof(SiparisYadaGonderilenAdet), ref fSiparisYadaGonderilenAdet, value); }
        }
        double fSiparisFiyat;
        public double SiparisFiyat
        {
            get { return fSiparisFiyat; }
            set { SetPropertyValue<double>(nameof(SiparisFiyat), ref fSiparisFiyat, value); }
        }
        Parabirimi fS_ParaBirimi;
        public Parabirimi S_ParaBirimi
        {
            get { return fS_ParaBirimi; }
            set { SetPropertyValue<Parabirimi>(nameof(S_ParaBirimi), ref fS_ParaBirimi, value); }
        }
        DateTime fS_Kur_Tarih;
        public DateTime S_Kur_Tarih
        {
            get { return fS_Kur_Tarih; }
            set { SetPropertyValue<DateTime>(nameof(S_Kur_Tarih), ref fS_Kur_Tarih, value); }
        }
        decimal fS_Kuru;
        public decimal S_Kuru
        {
            get { return fS_Kuru; }
            set { SetPropertyValue<decimal>(nameof(S_Kuru), ref fS_Kuru, value); }
        }
        double fS_Tplm_Dvz;
        public double S_Tplm_Dvz
        {
            get { return fS_Tplm_Dvz; }
            set { SetPropertyValue<double>(nameof(S_Tplm_Dvz), ref fS_Tplm_Dvz, value); }
        }
        double fS_Tplm_TL;
        public double S_Tplm_TL
        {
            get { return fS_Tplm_TL; }
            set { SetPropertyValue<double>(nameof(S_Tplm_TL), ref fS_Tplm_TL, value); }
        }
        string fS_Aciklama;
        public string S_Aciklama
        {
            get { return fS_Aciklama; }
            set { SetPropertyValue<string>(nameof(S_Aciklama), ref fS_Aciklama, value); }
        }
    }

}
