//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class SiparisKarti : XPObject
    {
        string ficSiparisNo;
        public string icSiparisNo
        {
            get { return ficSiparisNo; }
            set { SetPropertyValue<string>(nameof(icSiparisNo), ref ficSiparisNo, value); }
        }
        string fMusteriSiparisNo;
        public string MusteriSiparisNo
        {
            get { return fMusteriSiparisNo; }
            set { SetPropertyValue<string>(nameof(MusteriSiparisNo), ref fMusteriSiparisNo, value); }
        }
        ModelKarti fModelKarti;
        [Association(@"SiparisKartiReferencesModelKarti")]
        public ModelKarti ModelKarti
        {
            get { return fModelKarti; }
            set { SetPropertyValue<ModelKarti>(nameof(ModelKarti), ref fModelKarti, value); }
        }
        int fSiparisAdet;
        public int SiparisAdet
        {
            get { return fSiparisAdet; }
            set { SetPropertyValue<int>(nameof(SiparisAdet), ref fSiparisAdet, value); }
        }
        decimal fFiyat;
        public decimal Fiyat
        {
            get { return fFiyat; }
            set { SetPropertyValue<decimal>(nameof(Fiyat), ref fFiyat, value); }
        }
        decimal fToplamTutar;
        public decimal ToplamTutar
        {
            get { return fToplamTutar; }
            set { SetPropertyValue<decimal>(nameof(ToplamTutar), ref fToplamTutar, value); }
        }
        Parabirimi fParaBirimi;
        public Parabirimi ParaBirimi
        {
            get { return fParaBirimi; }
            set { SetPropertyValue<Parabirimi>(nameof(ParaBirimi), ref fParaBirimi, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fTemsilci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari Temsilci
        {
            get { return fTemsilci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(Temsilci), ref fTemsilci, value); }
        }
        DateTime ficTermin;
        public DateTime icTermin
        {
            get { return ficTermin; }
            set { SetPropertyValue<DateTime>(nameof(icTermin), ref ficTermin, value); }
        }
        DateTime fMusteriTermin;
        public DateTime MusteriTermin
        {
            get { return fMusteriTermin; }
            set { SetPropertyValue<DateTime>(nameof(MusteriTermin), ref fMusteriTermin, value); }
        }
        string fSiparis;
        public string Siparis
        {
            get { return fSiparis; }
            set { SetPropertyValue<string>(nameof(Siparis), ref fSiparis, value); }
        }
        Bedenler fBedenGrubu;
        public Bedenler BedenGrubu
        {
            get { return fBedenGrubu; }
            set { SetPropertyValue<Bedenler>(nameof(BedenGrubu), ref fBedenGrubu, value); }
        }
        string fArticle;
        public string Article
        {
            get { return fArticle; }
            set { SetPropertyValue<string>(nameof(Article), ref fArticle, value); }
        }
        Model_Maliyet fOnaylanmısModel;
        [Association(@"SiparisKartiReferencesModel_Maliyet")]
        public Model_Maliyet OnaylanmısModel
        {
            get { return fOnaylanmısModel; }
            set { SetPropertyValue<Model_Maliyet>(nameof(OnaylanmısModel), ref fOnaylanmısModel, value); }
        }
        int fKesimlenToplam;
        public int KesimlenToplam
        {
            get { return fKesimlenToplam; }
            set { SetPropertyValue<int>(nameof(KesimlenToplam), ref fKesimlenToplam, value); }
        }
        int fDikimToplam;
        public int DikimToplam
        {
            get { return fDikimToplam; }
            set { SetPropertyValue<int>(nameof(DikimToplam), ref fDikimToplam, value); }
        }
        int fPaketToplam;
        public int PaketToplam
        {
            get { return fPaketToplam; }
            set { SetPropertyValue<int>(nameof(PaketToplam), ref fPaketToplam, value); }
        }
        int fHatali;
        public int Hatali
        {
            get { return fHatali; }
            set { SetPropertyValue<int>(nameof(Hatali), ref fHatali, value); }
        }
        int fiade;
        public int iade
        {
            get { return fiade; }
            set { SetPropertyValue<int>(nameof(iade), ref fiade, value); }
        }
        int fReklamasyon;
        public int Reklamasyon
        {
            get { return fReklamasyon; }
            set { SetPropertyValue<int>(nameof(Reklamasyon), ref fReklamasyon, value); }
        }
        SiparisFoy fSiparisFoy;
        [Association(@"SiparisKartiReferencesSiparisFoy")]
        public SiparisFoy SiparisFoy
        {
            get { return fSiparisFoy; }
            set { SetPropertyValue<SiparisFoy>(nameof(SiparisFoy), ref fSiparisFoy, value); }
        }
        string fOMUZBOY;
        public string OMUZBOY
        {
            get { return fOMUZBOY; }
            set { SetPropertyValue<string>(nameof(OMUZBOY), ref fOMUZBOY, value); }
        }
        string fGOGUS;
        public string GOGUS
        {
            get { return fGOGUS; }
            set { SetPropertyValue<string>(nameof(GOGUS), ref fGOGUS, value); }
        }
        string fBEL;
        public string BEL
        {
            get { return fBEL; }
            set { SetPropertyValue<string>(nameof(BEL), ref fBEL, value); }
        }
        string fBASEN;
        public string BASEN
        {
            get { return fBASEN; }
            set { SetPropertyValue<string>(nameof(BASEN), ref fBASEN, value); }
        }
        string fGOGUSDUS;
        public string GOGUSDUS
        {
            get { return fGOGUSDUS; }
            set { SetPropertyValue<string>(nameof(GOGUSDUS), ref fGOGUSDUS, value); }
        }
        string fONBEDENBOYU;
        public string ONBEDENBOYU
        {
            get { return fONBEDENBOYU; }
            set { SetPropertyValue<string>(nameof(ONBEDENBOYU), ref fONBEDENBOYU, value); }
        }
        string fARKAYAKADUS;
        public string ARKAYAKADUS
        {
            get { return fARKAYAKADUS; }
            set { SetPropertyValue<string>(nameof(ARKAYAKADUS), ref fARKAYAKADUS, value); }
        }
        string fDISOMUZ;
        public string DISOMUZ
        {
            get { return fDISOMUZ; }
            set { SetPropertyValue<string>(nameof(DISOMUZ), ref fDISOMUZ, value); }
        }
        string fOMUZ;
        public string OMUZ
        {
            get { return fOMUZ; }
            set { SetPropertyValue<string>(nameof(OMUZ), ref fOMUZ, value); }
        }
        string fYAKADUS;
        public string YAKADUS
        {
            get { return fYAKADUS; }
            set { SetPropertyValue<string>(nameof(YAKADUS), ref fYAKADUS, value); }
        }
        string fKOLBOYU;
        public string KOLBOYU
        {
            get { return fKOLBOYU; }
            set { SetPropertyValue<string>(nameof(KOLBOYU), ref fKOLBOYU, value); }
        }
        string fBILEK;
        public string BILEK
        {
            get { return fBILEK; }
            set { SetPropertyValue<string>(nameof(BILEK), ref fBILEK, value); }
        }
        string fPAZU;
        public string PAZU
        {
            get { return fPAZU; }
            set { SetPropertyValue<string>(nameof(PAZU), ref fPAZU, value); }
        }
        string fACIKLAMA;
        [Size(SizeAttribute.Unlimited)]
        public string ACIKLAMA
        {
            get { return fACIKLAMA; }
            set { SetPropertyValue<string>(nameof(ACIKLAMA), ref fACIKLAMA, value); }
        }
        BedenOlculeri fBedenOlcu;
        public BedenOlculeri BedenOlcu
        {
            get { return fBedenOlcu; }
            set { SetPropertyValue<BedenOlculeri>(nameof(BedenOlcu), ref fBedenOlcu, value); }
        }
        Subeler fMSube;
        public Subeler MSube
        {
            get { return fMSube; }
            set { SetPropertyValue<Subeler>(nameof(MSube), ref fMSube, value); }
        }
        decimal fiskontoYuzde;
        public decimal iskontoYuzde
        {
            get { return fiskontoYuzde; }
            set { SetPropertyValue<decimal>(nameof(iskontoYuzde), ref fiskontoYuzde, value); }
        }
        decimal fiskontoTutar;
        public decimal iskontoTutar
        {
            get { return fiskontoTutar; }
            set { SetPropertyValue<decimal>(nameof(iskontoTutar), ref fiskontoTutar, value); }
        }
        SiparisDurumu fSprDurumu;
        public SiparisDurumu SprDurumu
        {
            get { return fSprDurumu; }
            set { SetPropertyValue<SiparisDurumu>(nameof(SprDurumu), ref fSprDurumu, value); }
        }
        [DevExpress.Xpo.PersistentAlias("SiparisFoy.Toptan")] // Added full namespace for clarity for the worker
        public bool Toptan
        {
            get { return (bool)(EvaluateAlias(nameof(Toptan)) ?? false); }
        }
        string fAYNA;
        public string AYNA
        {
            get { return fAYNA; }
            set { SetPropertyValue<string>(nameof(AYNA), ref fAYNA, value); }
        }
        string fYANBEDBOYU;
        public string YANBEDBOYU
        {
            get { return fYANBEDBOYU; }
            set { SetPropertyValue<string>(nameof(YANBEDBOYU), ref fYANBEDBOYU, value); }
        }
        string fBilekdirskarasi;
        public string Bilekdirskarasi
        {
            get { return fBilekdirskarasi; }
            set { SetPropertyValue<string>(nameof(Bilekdirskarasi), ref fBilekdirskarasi, value); }
        }
        bool fSprTamamlanmis;
        public bool SprTamamlanmis
        {
            get { return fSprTamamlanmis; }
            set { SetPropertyValue<bool>(nameof(SprTamamlanmis), ref fSprTamamlanmis, value); }
        }
        string fBOY;
        public string BOY
        {
            get { return fBOY; }
            set { SetPropertyValue<string>(nameof(BOY), ref fBOY, value); }
        }
        string fGogusAcikligi;
        public string GogusAcikligi
        {
            get { return fGogusAcikligi; }
            set { SetPropertyValue<string>(nameof(GogusAcikligi), ref fGogusAcikligi, value); }
        }
        string fSirtAcikligi;
        public string SirtAcikligi
        {
            get { return fSirtAcikligi; }
            set { SetPropertyValue<string>(nameof(SirtAcikligi), ref fSirtAcikligi, value); }
        }
        [Association(@"SiparisKartiReferencesAksesuarlar")]
        public XPCollection<Aksesuarlar> Aksesuarlars { get { return GetCollection<Aksesuarlar>(nameof(Aksesuarlars)); } }
        [Association(@"SiparisDetayReferencesSiparisKarti")]
        public XPCollection<SiparisDetay> SiparisDetays { get { return GetCollection<SiparisDetay>(nameof(SiparisDetays)); } }
        [Association(@"MusteriTerminReferencesSiparisKarti")]
        public XPCollection<Termin> MusteriTermins { get { return GetCollection<Termin>(nameof(MusteriTermins)); } }
        [Association(@"FaturalarReferencesSiparisKarti")]
        public XPCollection<Faturalar> Faturalars { get { return GetCollection<Faturalar>(nameof(Faturalars)); } }
        [Association(@"GunlukKesimReferencesSiparisKarti")]
        public XPCollection<GunlukKesim> GunlukKesims { get { return GetCollection<GunlukKesim>(nameof(GunlukKesims)); } }
        [Association(@"AksesuarSiparisReferencesSiparisKarti"), Aggregated]
        public XPCollection<AksesuarSiparis> AksesuarSiparisCollection { get { return GetCollection<AksesuarSiparis>(nameof(AksesuarSiparisCollection)); } }
        [Association(@"EtiketlerReferencesSiparisKarti"), Aggregated]
        public XPCollection<Etiketler> Etiketlers { get { return GetCollection<Etiketler>(nameof(Etiketlers)); } }
        [Association(@"BaskiReferencesSiparisKarti"), Aggregated]
        public XPCollection<Baski> Baskis { get { return GetCollection<Baski>(nameof(Baskis)); } }
        [Association(@"NakisReferencesSiparisKarti"), Aggregated]
        public XPCollection<Nakis> NakisCollection { get { return GetCollection<Nakis>(nameof(NakisCollection)); } }
        [Association(@"Kumas_SatinAlmaReferencesSiparisKarti"), Aggregated]
        public XPCollection<Kumas_SatinAlma> Kumas_SatinAlmas { get { return GetCollection<Kumas_SatinAlma>(nameof(Kumas_SatinAlmas)); } }
        [Association(@"SiparisislemlerReferencesSiparisKarti"), Aggregated]
        public XPCollection<Siparisislemler> Siparisislemlers { get { return GetCollection<Siparisislemler>(nameof(Siparisislemlers)); } }
        [Association(@"SiparisEkDosyalariReferencesSiparisKarti"), Aggregated]
        public XPCollection<SiparisEkDosyalari> SiparisEkDosyalaris { get { return GetCollection<SiparisEkDosyalari>(nameof(SiparisEkDosyalaris)); } }
        [Association(@"irsaliyelerReferencesSiparisKarti"), Aggregated]
        public XPCollection<irsaliyeler> irsaliyelers { get { return GetCollection<irsaliyeler>(nameof(irsaliyelers)); } }
        [Association(@"DikimReferencesSiparisKarti"), Aggregated]
        public XPCollection<Dikim> Dikims { get { return GetCollection<Dikim>(nameof(Dikims)); } }
        [Association(@"ProvaTakipReferencesSiparisKarti"), Aggregated]
        public XPCollection<ProvaTakip> ProvaTakips { get { return GetCollection<ProvaTakip>(nameof(ProvaTakips)); } }
        [Association(@"SiparisKontrolFormuReferencesSiparisKarti"), Aggregated]
        public XPCollection<SiparisKontrolFormu> SiparisKontrolFormus { get { return GetCollection<SiparisKontrolFormu>(nameof(SiparisKontrolFormus)); } }
        [Association(@"ModelEkstraIslemlerReferencesSiparisKarti"), Aggregated]
        public XPCollection<ModelEkstraIslemler> ModelEkstraIslemlers { get { return GetCollection<ModelEkstraIslemler>(nameof(ModelEkstraIslemlers)); } }
        [Association(@"SiparisKesimTablosuReferencesSiparisKarti"), Aggregated]
        public XPCollection<SiparisKesimTablosu> SiparisKesimTablosus { get { return GetCollection<SiparisKesimTablosu>(nameof(SiparisKesimTablosus)); } }
        [Association(@"SiparisEkResimlerReferencesSiparisKarti"), Aggregated]
        public XPCollection<SiparisEkResimler> SiparisEkResimlers { get { return GetCollection<SiparisEkResimler>(nameof(SiparisEkResimlers)); } }
    }

}
