//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class SiparisEkResimler : XPObject
    {
        byte[] fResim;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
    ListViewImageEditorCustomHeight = 40)]
        public byte[] Resim
        {
            get { return fResim; }
            set { SetPropertyValue<byte[]>(nameof(Resim), ref fResim, value); }
        }
        string fAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
        SiparisKarti fSiparisKarti;
        [Association(@"SiparisEkResimlerReferencesSiparisKarti")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue<SiparisKarti>(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }
    }

}
