//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{
    public enum OperasyonDurumu
    {
        Planlandi,
        Basladi,
        Tamamlandi,
        Beklemede
    }

    public partial class SiparisOperasyon : XPObject
    {
        SiparisKarti fSiparisKarti;
        [Association("SiparisKarti-SiparisOperasyon")]
        public SiparisKarti SiparisKarti
        {
            get { return fSiparisKarti; }
            set { SetPropertyValue(nameof(SiparisKarti), ref fSiparisKarti, value); }
        }

        ModelOperasyon fModelOperasyon;
        public ModelOperasyon ModelOperasyon
        {
            get { return fModelOperasyon; }
            set { SetPropertyValue(nameof(ModelOperasyon), ref fModelOperasyon, value); }
        }

        OperasyonDurumu fDurum;
        public OperasyonDurumu Durum
        {
            get { return fDurum; }
            set { SetPropertyValue(nameof(Durum), ref fDurum, value); }
        }

        DateTime fBaslamaTarihi;
        public DateTime BaslamaTarihi
        {
            get { return fBaslamaTarihi; }
            set { SetPropertyValue(nameof(BaslamaTarihi), ref fBaslamaTarihi, value); }
        }

        DateTime fBitisTarihi;
        public DateTime BitisTarihi
        {
            get { return fBitisTarihi; }
            set { SetPropertyValue(nameof(BitisTarihi), ref fBitisTarihi, value); }
        }

        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fSorumluPersonel;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari SorumluPersonel
        {
            get { return fSorumluPersonel; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(SorumluPersonel), ref fSorumluPersonel, value); }
        }

        [Association("SiparisOperasyon-FasonTakip"), Aggregated]
        public XPCollection<FasonTakip> FasonTakipler
        {
            get { return GetCollection<FasonTakip>(nameof(FasonTakipler)); }
        }
    }
}
