//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

	public partial class Stoklar : XPObject
	{
		ModelKarti fModelKarti;
		public ModelKarti ModelKarti
		{
			get { return fModelKarti; }
			set { SetPropertyValue<ModelKarti>(nameof(ModelKarti), ref fModelKarti, value); }
		}
		int fAdet;
		public int Adet
		{
			get { return fAdet; }
			set { SetPropertyValue<int>(nameof(Adet), ref fAdet, value); }
		}
		Depolar fDepoAdi;
		public Depolar DepoAdi
		{
			get { return fDepoAdi; }
			set { SetPropertyValue<Depolar>(nameof(DepoAdi), ref fDepoAdi, value); }
		}
		int fKiralamadakiAdet;
		public int KiralamadakiAdet
		{
			get { return fKiralamadakiAdet; }
			set { SetPropertyValue<int>(nameof(KiralamadakiAdet), ref fKiralamadakiAdet, value); }
		}
		int fDepodakiAdet;
		public int DepodakiAdet
		{
			get { return fDepodakiAdet; }
			set { SetPropertyValue<int>(nameof(DepodakiAdet), ref fDepodakiAdet, value); }
		}
	}

}
