//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Teklifler : XPObject
    {
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fTemsilci;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari Temsilci
        {
            get { return fTemsilci; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(Temsilci), ref fTemsilci, value); }
        }
        string fMusteri;
        public string Musteri
        {
            get { return fMusteri; }
            set { SetPropertyValue<string>(nameof(Musteri), ref fMusteri, value); }
        }
        string fTelefonu;
        public string Telefonu
        {
            get { return fTelefonu; }
            set { SetPropertyValue<string>(nameof(Telefonu), ref fTelefonu, value); }
        }
        DateTime fTarihSaat;
        public DateTime TarihSaat
        {
            get { return fTarihSaat; }
            set { SetPropertyValue<DateTime>(nameof(TarihSaat), ref fTarihSaat, value); }
        }
        [Association(@"TeklifDetaylariReferencesTeklifler"), Aggregated]
        public XPCollection<TeklifDetaylari> TeklifDetaylaris { get { return GetCollection<TeklifDetaylari>(nameof(TeklifDetaylaris)); } }
    }

}
