//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class Termin : XPObject
    {
        DateTime fMusteriTermin;
        public DateTime MusteriTermin
        {
            get { return fMusteriTermin; }
            set { SetPropertyValue<DateTime>(nameof(MusteriTermin), ref fMusteriTermin, value); }
        }
        DateTime ficTermin;
        public DateTime icTermin
        {
            get { return ficTermin; }
            set { SetPropertyValue<DateTime>(nameof(icTermin), ref ficTermin, value); }
        }
        int fYuklemeAdet;
        public int YuklemeAdet
        {
            get { return fYuklemeAdet; }
            set { SetPropertyValue<int>(nameof(YuklemeAdet), ref fYuklemeAdet, value); }
        }
        SiparisKarti fSiparis_To;
        [Association(@"MusteriTerminReferencesSiparisKarti")]
        public SiparisKarti Siparis_To
        {
            get { return fSiparis_To; }
            set { SetPropertyValue<SiparisKarti>(nameof(Siparis_To), ref fSiparis_To, value); }
        }
    }

}
