//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ZekiKod.Module.BusinessObjects.ZekiKodDB
{

    public partial class UretimBandi : XPObject
    {
        Bandi fBand;
        [Association(@"UretimBandiReferencesBandi")]
        public Bandi Band
        {
            get { return fBand; }
            set { SetPropertyValue<Bandi>(nameof(Band), ref fBand, value); }
        }
        int fSiralama;
        public int Siralama
        {
            get { return fSiralama; }
            set { SetPropertyValue<int>(nameof(Siralama), ref fSiralama, value); }
        }
        Makinalar fMakina;
        public Makinalar Makina
        {
            get { return fMakina; }
            set { SetPropertyValue<Makinalar>(nameof(Makina), ref fMakina, value); }
        }
        Operasyonlar fOperasyon;
        public Operasyonlar Operasyon
        {
            get { return fOperasyon; }
            set { SetPropertyValue<Operasyonlar>(nameof(Operasyon), ref fOperasyon, value); }
        }
        Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari fPersonel;
        public Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari Personel
        {
            get { return fPersonel; }
            set { SetPropertyValue<Sirketiz.Module.BusinessObjects.Sirket_izDB.kisi_kartlari>(nameof(Personel), ref fPersonel, value); }
        }
    }

}
