//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class bordro_alani : XPObject
    {
        string faciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        bool fgun;
        [DevExpress.Xpo.DisplayName(@"Gün")]
        public bool gun
        {
            get { return fgun; }
            set { SetPropertyValue<bool>(nameof(gun), ref fgun, value); }
        }
        bool fsaat;
        [DevExpress.Xpo.DisplayName(@"Saat")]
        public bool saat
        {
            get { return fsaat; }
            set { SetPropertyValue<bool>(nameof(saat), ref fsaat, value); }
        }
        bool fucret;
        [DevExpress.Xpo.DisplayName(@"Ücret")]
        public bool ucret
        {
            get { return fucret; }
            set { SetPropertyValue<bool>(nameof(ucret), ref fucret, value); }
        }
        BordroTipi ftip;
        public enum BordroTipi
        {
            Normal_Çalışma,
            FazlaMesai,
            Artı_Hesaplar,
            Eksi_Hesaplar,
            Bilgi_Ücrete_Eklenmez,
            Normal_Ek_Mesailer
        }
		public BordroTipi tip
        {
            get { return ftip; }
            set { SetPropertyValue<BordroTipi>(nameof(tip), ref ftip, value); }
        }
    }

}
