//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class Cihazlar : XPObject
    {
        int fCihazNo;
        public int CihazNo
        {
            get { return fCihazNo; }
            set { SetPropertyValue<int>(nameof(CihazNo), ref fCihazNo, value); }
        }
        string fCihazAdi;
        public string CihazAdi
        {
            get { return fCihazAdi; }
            set { SetPropertyValue<string>(nameof(CihazAdi), ref fCihazAdi, value); }
        }
        CihazModeli fCihazModel;
        public enum CihazModeli
        {
            Parmakizi,
            YüzTanıma

        }
		public CihazModeli CihazModel
        {
            get { return fCihazModel; }
            set { SetPropertyValue<CihazModeli>(nameof(CihazModel), ref fCihazModel, value); }
        }
        string fIpAdresi;
        public string IpAdresi
        {
            get { return fIpAdresi; }
            set { SetPropertyValue<string>(nameof(IpAdresi), ref fIpAdresi, value); }
        }
        string fCihazPort;
        public string CihazPort
        {
            get { return fCihazPort; }
            set { SetPropertyValue<string>(nameof(CihazPort), ref fCihazPort, value); }
        }
        string fServerPort;
        public string ServerPort
        {
            get { return fServerPort; }
            set { SetPropertyValue<string>(nameof(ServerPort), ref fServerPort, value); }
        }
        CihazDurum fDurumu;
        public enum CihazDurum
        {
            GirişÇıkış,
            Giriş,
            Çıkış

        }
		public CihazDurum Durumu
        {
            get { return fDurumu; }
            set { SetPropertyValue<CihazDurum>(nameof(Durumu), ref fDurumu, value); }
        }
        KullanimYeri fKullanımYeri;
        public enum KullanimYeri
        {
            Genel,
            Tuvalet,
            Yemekhane

        }
		public KullanimYeri KullanımYeri
        {
            get { return fKullanımYeri; }
            set { SetPropertyValue<KullanimYeri>(nameof(KullanımYeri), ref fKullanımYeri, value); }
        }
    }

}
