//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(kisi_kartlari),
            typeof(kisi_grscks),
            typeof(departman),
            typeof(bolum),
            typeof(servis),
            typeof(sirket),
            typeof(kisi_izin),
            typeof(kisi_prim),
            typeof(kisi_avans),
            typeof(ozelkod),
            typeof(vardiya),
            typeof(vardiya_detay),
            typeof(puantaj_gun),
            typeof(plan_genel),
            typeof(plan_genel_detay),
            typeof(tatil_tablosu),
            typeof(puantaj_gun_detay),
            typeof(bordro_alani),
            typeof(kisi_maas),
            typeof(plan_ozel),
            typeof(meslek_kodu),
            typeof(eksikgunneden),
            typeof(Puantaj_mola),
            typeof(agi_tablosu),
            typeof(Cihazlar),
            typeof(TanimsizKartlar),
            typeof(kisi_wc_grscks)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
#warning We recommend moving the connection string out of your source code (for instance, to a configuration file) to improve your application's maintainability and security.
        public const string ConnectionString = "XpoProvider=MSSqlServer;data source=.;user id=sa;password=9726;initial catalog=ZekiKod-PersonelDB;Persist Security Info=true";
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
