//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class eksikgunneden : XPObject
    {
        string feksikgunkodu;
        public string eksikgunkodu
        {
            get { return feksikgunkodu; }
            set { SetPropertyValue<string>(nameof(eksikgunkodu), ref feksikgunkodu, value); }
        }
        string feksikgunad;
        public string eksikgunad
        {
            get { return feksikgunad; }
            set { SetPropertyValue<string>(nameof(eksikgunad), ref feksikgunad, value); }
        }
    }

}
