//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class kisi_wc_grscks : XPObject
    {
        kisi_kartlari fkisi_kartlari_to;
        [Association(@"kisi_wc_grscksReferenceskisi_kartlari")]
        public kisi_kartlari kisi_kartlari_to
        {
            get { return fkisi_kartlari_to; }
            set { SetPropertyValue<kisi_kartlari>(nameof(kisi_kartlari_to), ref fkisi_kartlari_to, value); }
        }
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        DateTime? fGiris;
        public DateTime? Giris
        {
            get { return fGiris; }
            set { SetPropertyValue<DateTime?>(nameof(Giris), ref fGiris, value); }
        }
        DateTime? fCikis;
        public DateTime? Cikis
        {
            get { return fCikis; }
            set { SetPropertyValue<DateTime?>(nameof(Cikis), ref fCikis, value); }
        }
        TimeSpan ficeridekiSure;
        public TimeSpan iceridekiSure
        {
            get { return ficeridekiSure; }
            set { SetPropertyValue<TimeSpan>(nameof(iceridekiSure), ref ficeridekiSure, value); }
        }
    }

}
