//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class kisi_maas : XPObject
    {
        DateTime ftarih;
        [DevExpress.Xpo.DisplayName(@"Tarih")]
        public DateTime tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<DateTime>(nameof(tarih), ref ftarih, value); }
        }
        decimal fucret;
        [DevExpress.Xpo.DisplayName(@"Ücret")]
        public decimal ucret
        {
            get { return fucret; }
            set { SetPropertyValue<decimal>(nameof(ucret), ref fucret, value); }
        }
        kisi_kartlari fkisi_kartlari_to;
        [Association(@"kisi_maasReferenceskisi_kartlari")]
        public kisi_kartlari kisi_kartlari_to
        {
            get { return fkisi_kartlari_to; }
            set { SetPropertyValue<kisi_kartlari>(nameof(kisi_kartlari_to), ref fkisi_kartlari_to, value); }
        }
    }

}
