//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class kisi_izin : XPObject
    {
        DateTime ftarih;
        [DevExpress.Xpo.DisplayName(@"Tarih")]
        public DateTime tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<DateTime>(nameof(tarih), ref ftarih, value); }
        }
        DateTime ftarihine;
        [DevExpress.Xpo.DisplayName(@"Tarihine")]
        public DateTime tarihine
        {
            get { return ftarihine; }
            set { SetPropertyValue<DateTime>(nameof(tarihine), ref ftarihine, value); }
        }
        TimeSpan fgidis_saat;
        [DevExpress.Xpo.DisplayName(@"Gidiş Saati")]
        public TimeSpan gidis_saat
        {
            get { return fgidis_saat; }
            set { SetPropertyValue<TimeSpan>(nameof(gidis_saat), ref fgidis_saat, value); }
        }
        TimeSpan fgelis_saat;
        [DevExpress.Xpo.DisplayName(@"Geliş Saati")]
        public TimeSpan gelis_saat
        {
            get { return fgelis_saat; }
            set { SetPropertyValue<TimeSpan>(nameof(gelis_saat), ref fgelis_saat, value); }
        }
        bool fsaatlik;
        [DevExpress.Xpo.DisplayName(@"Saatlik")]
        public bool saatlik
        {
            get { return fsaatlik; }
            set { SetPropertyValue<bool>(nameof(saatlik), ref fsaatlik, value); }
        }
        string fAciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
        kisi_kartlari fkisi_kartlari_to;
        [Association(@"kisi_izinReferenceskisi_kartlari")]
        public kisi_kartlari kisi_kartlari_to
        {
            get { return fkisi_kartlari_to; }
            set { SetPropertyValue<kisi_kartlari>(nameof(kisi_kartlari_to), ref fkisi_kartlari_to, value); }
        }
        tatil_tablosu fizintipi;
        [DevExpress.Xpo.DisplayName(@"İzin Türü")]
        public tatil_tablosu izintipi
        {
            get { return fizintipi; }
            set { SetPropertyValue<tatil_tablosu>(nameof(izintipi), ref fizintipi, value); }
        }
    }

}
