//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class kisi_kartlari : XPObject
    {
        string fkartno;
        [DevExpress.Xpo.DisplayName(@"Kart No")]
        public string kartno
        {
            get { return fkartno; }
            set { SetPropertyValue<string>(nameof(kartno), ref fkartno, value); }
        }
        string fadi;
        [DevExpress.Xpo.DisplayName(@"Adı")]
        public string adi
        {
            get { return fadi; }
            set { SetPropertyValue<string>(nameof(adi), ref fadi, value); }
        }
        string fsoyadi;
        [DevExpress.Xpo.DisplayName(@"Soyadı")]
        public string soyadi
        {
            get { return fsoyadi; }
            set { SetPropertyValue<string>(nameof(soyadi), ref fsoyadi, value); }
        }
        string fsicilno;
        [DevExpress.Xpo.DisplayName(@"Sicil No")]
        public string sicilno
        {
            get { return fsicilno; }
            set { SetPropertyValue<string>(nameof(sicilno), ref fsicilno, value); }
        }
        string fsgkno;
        [DevExpress.Xpo.DisplayName(@"Sgk No")]
        public string sgkno
        {
            get { return fsgkno; }
            set { SetPropertyValue<string>(nameof(sgkno), ref fsgkno, value); }
        }
        DateTime fgiristarihi;
        [DevExpress.Xpo.DisplayName(@"Giriş Tarihi")]
        public DateTime giristarihi
        {
            get { return fgiristarihi; }
            set { SetPropertyValue<DateTime>(nameof(giristarihi), ref fgiristarihi, value); }
        }
        DateTime fcikistarihi;
        [DevExpress.Xpo.DisplayName(@"Çıkış Tarihi")]
        public DateTime cikistarihi
        {
            get { return fcikistarihi; }
            set { SetPropertyValue<DateTime>(nameof(cikistarihi), ref fcikistarihi, value); }
        }
        string ftcno;
        [Size(11)]
        [DevExpress.Xpo.DisplayName(@"Tc No")]
        public string tcno
        {
            get { return ftcno; }
            set { SetPropertyValue<string>(nameof(tcno), ref ftcno, value); }
        }
        string fnot;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Not")]
        public string not
        {
            get { return fnot; }
            set { SetPropertyValue<string>(nameof(not), ref fnot, value); }
        }
        sirket fsirketid;
        [DevExpress.Xpo.DisplayName(@"Şirket")]
        public sirket sirketid
        {
            get { return fsirketid; }
            set { SetPropertyValue<sirket>(nameof(sirketid), ref fsirketid, value); }
        }
        departman fdepartmanid;
        [DevExpress.Xpo.DisplayName(@"Departman")]
        public departman departmanid
        {
            get { return fdepartmanid; }
            set { SetPropertyValue<departman>(nameof(departmanid), ref fdepartmanid, value); }
        }
        bolum fbolumid;
        [DevExpress.Xpo.DisplayName(@"Bölüm")]
        public bolum bolumid
        {
            get { return fbolumid; }
            set { SetPropertyValue<bolum>(nameof(bolumid), ref fbolumid, value); }
        }
        plan_genel fhesapkodid;
        [DevExpress.Xpo.DisplayName(@"Hesap Grubu")]
        public plan_genel hesapkodid
        {
            get { return fhesapkodid; }
            set { SetPropertyValue<plan_genel>(nameof(hesapkodid), ref fhesapkodid, value); }
        }
        servis fservisid;
        [DevExpress.Xpo.DisplayName(@"Servis")]
        public servis servisid
        {
            get { return fservisid; }
            set { SetPropertyValue<servis>(nameof(servisid), ref fservisid, value); }
        }
        byte[] fresim;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Xpo.DisplayName(@"Resim")]
        [DevExpress.Persistent.Base.VisibleInListView(true)]
        [DevExpress.Persistent.Base.ImageEditor(ListViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit,
   DetailViewImageEditorMode = DevExpress.Persistent.Base.ImageEditorMode.PictureEdit)]
        public byte[] resim
        {
            get { return fresim; }
            set { SetPropertyValue<byte[]>(nameof(resim), ref fresim, value); }
        }
        meslek_kodu fmeslekkodu;
        [DevExpress.Xpo.DisplayName(@"Meslek Kodu")]
        public meslek_kodu meslekkodu
        {
            get { return fmeslekkodu; }
            set { SetPropertyValue<meslek_kodu>(nameof(meslekkodu), ref fmeslekkodu, value); }
        }
        Cinsiyet fcinsiyet;
        public enum Cinsiyet
        {
            Seçiniz,
            Bay,
            Bayan

        }
		public Cinsiyet cinsiyet
        {
            get { return fcinsiyet; }
            set { SetPropertyValue<Cinsiyet>(nameof(cinsiyet), ref fcinsiyet, value); }
        }
        [PersistentAlias("[adi] + ' ' + [soyadi]")]
        public string AdSoyad
        {
            get { return (string)(EvaluateAlias(nameof(AdSoyad))); }
        }
        [Association(@"kisi_grscksReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_grscks> kisi_grsckss { get { return GetCollection<kisi_grscks>(nameof(kisi_grsckss)); } }
        [Association(@"kisi_izinReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_izin> kisi_izins { get { return GetCollection<kisi_izin>(nameof(kisi_izins)); } }
        [Association(@"kisi_avansReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_avans> kisi_avanss { get { return GetCollection<kisi_avans>(nameof(kisi_avanss)); } }
        [Association(@"kisi_primReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_prim> kisi_prims { get { return GetCollection<kisi_prim>(nameof(kisi_prims)); } }
        [Association(@"kisi_maasReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_maas> kisi_maass { get { return GetCollection<kisi_maas>(nameof(kisi_maass)); } }
        [Association(@"plan_ozelReferenceskisi_kartlari"), Aggregated]
        public XPCollection<plan_ozel> plan_ozels { get { return GetCollection<plan_ozel>(nameof(plan_ozels)); } }
        [Association(@"kisi_wc_grscksReferenceskisi_kartlari"), Aggregated]
        public XPCollection<kisi_wc_grscks> kisi_wc_grsckss { get { return GetCollection<kisi_wc_grscks>(nameof(kisi_wc_grsckss)); } }
    }

}
