//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class kisi_grscks : XPObject
    {
        DateTime ftarih;
        [DevExpress.Xpo.DisplayName(@"Tarih")]
        public DateTime tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<DateTime>(nameof(tarih), ref ftarih, value); }
        }
        DateTime? fgiris_saat;
        [DevExpress.Xpo.DisplayName(@"Giriş Saati")]
        public DateTime? giris_saat
        {
            get { return fgiris_saat; }
            set { SetPropertyValue<DateTime?>(nameof(giris_saat), ref fgiris_saat, value); }
        }
        DateTime? fcikis_saat;
        [DevExpress.Xpo.DisplayName(@"Çıkış Saati")]
        public DateTime? cikis_saat
        {
            get { return fcikis_saat; }
            set { SetPropertyValue<DateTime?>(nameof(cikis_saat), ref fcikis_saat, value); }
        }
        short felle_giris;
        public short elle_giris
        {
            get { return felle_giris; }
            set { SetPropertyValue<short>(nameof(elle_giris), ref felle_giris, value); }
        }
        short felle_cikis;
        public short elle_cikis
        {
            get { return felle_cikis; }
            set { SetPropertyValue<short>(nameof(elle_cikis), ref felle_cikis, value); }
        }
        string fgiris_kapi;
        public string giris_kapi
        {
            get { return fgiris_kapi; }
            set { SetPropertyValue<string>(nameof(giris_kapi), ref fgiris_kapi, value); }
        }
        string fcikis_kapi;
        public string cikis_kapi
        {
            get { return fcikis_kapi; }
            set { SetPropertyValue<string>(nameof(cikis_kapi), ref fcikis_kapi, value); }
        }
        kisi_kartlari fkisi_kartlari_to;
        [Association(@"kisi_grscksReferenceskisi_kartlari")]
        public kisi_kartlari kisi_kartlari_to
        {
            get { return fkisi_kartlari_to; }
            set { SetPropertyValue<kisi_kartlari>(nameof(kisi_kartlari_to), ref fkisi_kartlari_to, value); }
        }
        [Persistent(@"Normal_Mesai")]
        string fNormal_Mesai;
        [PersistentAlias("fNormal_Mesai")]
        public string Normal_Mesai
        {
            get { return fNormal_Mesai; }
        }
        TimeSpan? fFazla_Mesai;
        public TimeSpan? Fazla_Mesai
        {
            get { return fFazla_Mesai; }
            set { SetPropertyValue<TimeSpan?>(nameof(Fazla_Mesai), ref fFazla_Mesai, value); }
        }
        TimeSpan? fEksik_Mesai;
        public TimeSpan? Eksik_Mesai
        {
            get { return fEksik_Mesai; }
            set { SetPropertyValue<TimeSpan?>(nameof(Eksik_Mesai), ref fEksik_Mesai, value); }
        }
        bool fDegisim;
        public bool Degisim
        {
            get { return fDegisim; }
            set { SetPropertyValue<bool>(nameof(Degisim), ref fDegisim, value); }
        }
        string fUcret;
        [DevExpress.Xpo.DisplayName(@"Ücret")]
        public string Ucret
        {
            get { return fUcret; }
            set { SetPropertyValue<string>(nameof(Ucret), ref fUcret, value); }
        }
        puantaj_gun fPuantajGun;
        public puantaj_gun PuantajGun
        {
            get { return fPuantajGun; }
            set { SetPropertyValue<puantaj_gun>(nameof(PuantajGun), ref fPuantajGun, value); }
        }
    }

}
