//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class meslek_kodu : XPObject
    {
        string fmeslekkodu;
        [DevExpress.Xpo.DisplayName(@"Meslek Kodu")]
        public string meslekkodu
        {
            get { return fmeslekkodu; }
            set { SetPropertyValue<string>(nameof(meslekkodu), ref fmeslekkodu, value); }
        }
        string fmeslek_adi;
        [DevExpress.Xpo.DisplayName(@"Meslek Adı")]
        public string meslek_adi
        {
            get { return fmeslek_adi; }
            set { SetPropertyValue<string>(nameof(meslek_adi), ref fmeslek_adi, value); }
        }
    }

}
