//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class plan_ozel : XPObject
    {
        string ftarih;
        [DevExpress.Xpo.DisplayName(@"Tarih")]
        public string tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<string>(nameof(tarih), ref ftarih, value); }
        }
        puantaj_gun fmesai_id;
        [DevExpress.Xpo.DisplayName(@"Puantaj Gün")]
        public puantaj_gun mesai_id
        {
            get { return fmesai_id; }
            set { SetPropertyValue<puantaj_gun>(nameof(mesai_id), ref fmesai_id, value); }
        }
        kisi_kartlari fkisi_kartlari_to;
        [Association(@"plan_ozelReferenceskisi_kartlari")]
        public kisi_kartlari kisi_kartlari_to
        {
            get { return fkisi_kartlari_to; }
            set { SetPropertyValue<kisi_kartlari>(nameof(kisi_kartlari_to), ref fkisi_kartlari_to, value); }
        }
    }

}
