//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class plan_genel : XPObject
    {
        string faciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        [Association(@"plan_genel_detayReferencesplan_genel"), Aggregated]
        public XPCollection<plan_genel_detay> plan_genel_detays { get { return GetCollection<plan_genel_detay>(nameof(plan_genel_detays)); } }
    }

}
