//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class plan_genel_detay : XPObject
    {
        DateTime ftarih;
        [DevExpress.Xpo.DisplayName(@"Tarih")]
        public DateTime tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<DateTime>(nameof(tarih), ref ftarih, value); }
        }
        plan_genel fplangenel_to;
        [Association(@"plan_genel_detayReferencesplan_genel")]
        public plan_genel plangenel_to
        {
            get { return fplangenel_to; }
            set { SetPropertyValue<plan_genel>(nameof(plangenel_to), ref fplangenel_to, value); }
        }
        vardiya fvardiya_id;
        [DevExpress.Xpo.DisplayName(@"Vardiya")]
        public vardiya vardiya_id
        {
            get { return fvardiya_id; }
            set { SetPropertyValue<vardiya>(nameof(vardiya_id), ref fvardiya_id, value); }
        }
    }

}
