//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class puantaj_gun : XPObject
    {
        string faciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        TimeSpan? fgun_donum;
        [DevExpress.Xpo.DisplayName(@"Gun Dönümü")]
        public TimeSpan? gun_donum
        {
            get { return fgun_donum; }
            set { SetPropertyValue<TimeSpan?>(nameof(gun_donum), ref fgun_donum, value); }
        }
        TimeSpan? fgiris_saat;
        [DevExpress.Xpo.DisplayName(@"Giriş Saati")]
        public TimeSpan? giris_saat
        {
            get { return fgiris_saat; }
            set { SetPropertyValue<TimeSpan?>(nameof(giris_saat), ref fgiris_saat, value); }
        }
        TimeSpan? fcikis_saat;
        [DevExpress.Xpo.DisplayName(@"Çıkış Saati")]
        public TimeSpan? cikis_saat
        {
            get { return fcikis_saat; }
            set { SetPropertyValue<TimeSpan?>(nameof(cikis_saat), ref fcikis_saat, value); }
        }
        TimeSpan? ferken_gelme;
        [DevExpress.Xpo.DisplayName(@"Erken Gelme")]
        public TimeSpan? erken_gelme
        {
            get { return ferken_gelme; }
            set { SetPropertyValue<TimeSpan?>(nameof(erken_gelme), ref ferken_gelme, value); }
        }
        TimeSpan? fgec_gelme;
        [DevExpress.Xpo.DisplayName(@"Geç Gelme")]
        public TimeSpan? gec_gelme
        {
            get { return fgec_gelme; }
            set { SetPropertyValue<TimeSpan?>(nameof(gec_gelme), ref fgec_gelme, value); }
        }
        TimeSpan? ferken_cikma;
        [DevExpress.Xpo.DisplayName(@"Erken Çıkma")]
        public TimeSpan? erken_cikma
        {
            get { return ferken_cikma; }
            set { SetPropertyValue<TimeSpan?>(nameof(erken_cikma), ref ferken_cikma, value); }
        }
        TimeSpan? fgunkacsaat;
        [DevExpress.Xpo.DisplayName(@"Bir Gün Kaç Saat")]
        public TimeSpan? gunkacsaat
        {
            get { return fgunkacsaat; }
            set { SetPropertyValue<TimeSpan?>(nameof(gunkacsaat), ref fgunkacsaat, value); }
        }
        [Association(@"puantaj_gun_detayReferencespuantaj_gun"), Aggregated]
        public XPCollection<puantaj_gun_detay> puantaj_gun_detays { get { return GetCollection<puantaj_gun_detay>(nameof(puantaj_gun_detays)); } }
        [Association(@"Puantaj_molaReferencespuantaj_gun"), Aggregated]
        public XPCollection<Puantaj_mola> Puantaj_molas { get { return GetCollection<Puantaj_mola>(nameof(Puantaj_molas)); } }
    }

}
