//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class puantaj_gun_detay : XPObject
    {
        bordro_alani fbordroid;
        [DevExpress.Xpo.DisplayName(@"Bordro Alanı")]
        public bordro_alani bordroid
        {
            get { return fbordroid; }
            set { SetPropertyValue<bordro_alani>(nameof(bordroid), ref fbordroid, value); }
        }
        TimeSpan? fbasla;
        [DevExpress.Xpo.DisplayName(@"Başlama Saati")]
        public TimeSpan? basla
        {
            get { return fbasla; }
            set { SetPropertyValue<TimeSpan?>(nameof(basla), ref fbasla, value); }
        }
        TimeSpan? fbitis;
        [DevExpress.Xpo.DisplayName(@"Bitiş Saati")]
        public TimeSpan? bitis
        {
            get { return fbitis; }
            set { SetPropertyValue<TimeSpan?>(nameof(bitis), ref fbitis, value); }
        }
        TimeSpan? fmin;
        [DevExpress.Xpo.DisplayName(@"Min. Tölerans")]
        public TimeSpan? min
        {
            get { return fmin; }
            set { SetPropertyValue<TimeSpan?>(nameof(min), ref fmin, value); }
        }
        TimeSpan? fmax;
        [DevExpress.Xpo.DisplayName(@"Max. Çalışma")]
        public TimeSpan? max
        {
            get { return fmax; }
            set { SetPropertyValue<TimeSpan?>(nameof(max), ref fmax, value); }
        }
        TimeSpan? fekle;
        [DevExpress.Xpo.DisplayName(@"Ekle")]
        public TimeSpan? ekle
        {
            get { return fekle; }
            set { SetPropertyValue<TimeSpan?>(nameof(ekle), ref fekle, value); }
        }
        int fcarpan;
        [DevExpress.Xpo.DisplayName(@"Çarpan")]
        public int carpan
        {
            get { return fcarpan; }
            set { SetPropertyValue<int>(nameof(carpan), ref fcarpan, value); }
        }
        string fucret;
        [DevExpress.Xpo.DisplayName(@"Ücret")]
        public string ucret
        {
            get { return fucret; }
            set { SetPropertyValue<string>(nameof(ucret), ref fucret, value); }
        }
        puantaj_gun fpuantaj_gun_to;
        [Association(@"puantaj_gun_detayReferencespuantaj_gun")]
        public puantaj_gun puantaj_gun_to
        {
            get { return fpuantaj_gun_to; }
            set { SetPropertyValue<puantaj_gun>(nameof(puantaj_gun_to), ref fpuantaj_gun_to, value); }
        }
    }

}
