//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class Puantaj_mola : XPObject
    {
        TimeSpan fgiris;
        [DevExpress.Xpo.DisplayName(@"Giriş Saat")]
        public TimeSpan giris
        {
            get { return fgiris; }
            set { SetPropertyValue<TimeSpan>(nameof(giris), ref fgiris, value); }
        }
        TimeSpan fcikis;
        [DevExpress.Xpo.DisplayName(@"Çıkış Saat")]
        public TimeSpan cikis
        {
            get { return fcikis; }
            set { SetPropertyValue<TimeSpan>(nameof(cikis), ref fcikis, value); }
        }
        string faciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        puantaj_gun fpuantajgun_to;
        [Association(@"Puantaj_molaReferencespuantaj_gun")]
        public puantaj_gun puantajgun_to
        {
            get { return fpuantajgun_to; }
            set { SetPropertyValue<puantaj_gun>(nameof(puantajgun_to), ref fpuantajgun_to, value); }
        }
    }

}
