//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class TanimsizKartlar : XPObject
    {
        string fKartNo;
        public string KartNo
        {
            get { return fKartNo; }
            set { SetPropertyValue<string>(nameof(KartNo), ref fKartNo, value); }
        }
        string fTarih_Saat;
        public string Tarih_Saat
        {
            get { return fTarih_Saat; }
            set { SetPropertyValue<string>(nameof(Tarih_Saat), ref fTarih_Saat, value); }
        }
        string fDurumu;
        public string Durumu
        {
            get { return fDurumu; }
            set { SetPropertyValue<string>(nameof(Durumu), ref fDurumu, value); }
        }
        string fCihazNo;
        public string CihazNo
        {
            get { return fCihazNo; }
            set { SetPropertyValue<string>(nameof(CihazNo), ref fCihazNo, value); }
        }
        string fHataKodu;
        public string HataKodu
        {
            get { return fHataKodu; }
            set { SetPropertyValue<string>(nameof(HataKodu), ref fHataKodu, value); }
        }
    }

}
