//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class tatil_tablosu : XPObject
    {
        string faciklama;
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        TimeSpan fhakedilen_sure;
        [DevExpress.Xpo.DisplayName(@"Hakedilen Süre")]
        public TimeSpan hakedilen_sure
        {
            get { return fhakedilen_sure; }
            set { SetPropertyValue<TimeSpan>(nameof(hakedilen_sure), ref fhakedilen_sure, value); }
        }
        bordro_alani fbordro_id;
        [DevExpress.Xpo.DisplayName(@"Bordro Alanı")]
        public bordro_alani bordro_id
        {
            get { return fbordro_id; }
            set { SetPropertyValue<bordro_alani>(nameof(bordro_id), ref fbordro_id, value); }
        }
        bool fsure_tipi;
        [DevExpress.Xpo.DisplayName(@"Günlük Normal Saati Esas Al")]
        public bool sure_tipi
        {
            get { return fsure_tipi; }
            set { SetPropertyValue<bool>(nameof(sure_tipi), ref fsure_tipi, value); }
        }
        string fucret_tipi;
        [DevExpress.Xpo.DisplayName(@"Ücret Tipi")]
        public string ucret_tipi
        {
            get { return fucret_tipi; }
            set { SetPropertyValue<string>(nameof(ucret_tipi), ref fucret_tipi, value); }
        }
        string ftatil_tipi;
        [DevExpress.Xpo.DisplayName(@"Tatil Tipi")]
        public string tatil_tipi
        {
            get { return ftatil_tipi; }
            set { SetPropertyValue<string>(nameof(tatil_tipi), ref ftatil_tipi, value); }
        }
        string fhesap_tipi;
        [DevExpress.Xpo.DisplayName(@"Hesap Tipi")]
        public string hesap_tipi
        {
            get { return fhesap_tipi; }
            set { SetPropertyValue<string>(nameof(hesap_tipi), ref fhesap_tipi, value); }
        }
    }

}
