//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class vardiya_detay : XPObject
    {
        TimeSpan fbaslangic;
        [DevExpress.Xpo.DisplayName(@"Başlangıç")]
        public TimeSpan baslangic
        {
            get { return fbaslangic; }
            set { SetPropertyValue<TimeSpan>(nameof(baslangic), ref fbaslangic, value); }
        }
        TimeSpan fbitis;
        [DevExpress.Xpo.DisplayName(@"Bitiş")]
        public TimeSpan bitis
        {
            get { return fbitis; }
            set { SetPropertyValue<TimeSpan>(nameof(bitis), ref fbitis, value); }
        }
        puantaj_gun fpuantajgun_id;
        [DevExpress.Xpo.DisplayName(@"Puantaj Gün")]
        public puantaj_gun puantajgun_id
        {
            get { return fpuantajgun_id; }
            set { SetPropertyValue<puantaj_gun>(nameof(puantajgun_id), ref fpuantajgun_id, value); }
        }
        tatil_tablosu ftatil_id;
        [DevExpress.Xpo.DisplayName(@"Tatil Tablosu")]
        public tatil_tablosu tatil_id
        {
            get { return ftatil_id; }
            set { SetPropertyValue<tatil_tablosu>(nameof(tatil_id), ref ftatil_id, value); }
        }
        vardiya fvardiya_to;
        [Association(@"vardiya_detayReferencesvardiya")]
        public vardiya vardiya_to
        {
            get { return fvardiya_to; }
            set { SetPropertyValue<vardiya>(nameof(vardiya_to), ref fvardiya_to, value); }
        }
    }

}
