//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sirketiz.Module.BusinessObjects.Sirket_izDB
{

    public partial class vardiya : XPObject
    {
        string faciklama;
        [DevExpress.Xpo.DisplayName(@"Açıklama")]
        public string aciklama
        {
            get { return faciklama; }
            set { SetPropertyValue<string>(nameof(aciklama), ref faciklama, value); }
        }
        [Association(@"vardiya_detayReferencesvardiya"), Aggregated]
        public XPCollection<vardiya_detay> vardiya_detays { get { return GetCollection<vardiya_detay>(nameof(vardiya_detays)); } }
    }

}
